### ISSUE TITLE
@import with blank file

### ISSUE THREAD

**Issue by lstebner** [bdkjones/CodeKit-1-Old#10]
When you @import a completely blank file, it seems to be ok, but if you have any sort of "invisible characters" (like spaces or line breaks) it breaks the next file that is import'ed.

For example, say my "main.less" looks like this:
@import 'one.less';
@import 'two.less';
@import 'three.less';
@Import 'four.less';

If 'two.less' contains only space characters, but all the other files have a few styles in htem, the final compiled 'main.css' won't have any of the content from 'three.less'. 

I'm guessing regex issue when reading file contents?

**Comment by bdkjones** [comment]
Can you send me a set of example files that demonstrate the issue, please? Thanks!

**Comment by bdkjones** [comment]
Haha, oh regex. We're down in the basement of C when we're scanning files for import statements, my friend. The only lower we could go would be assembly, machine code, or flat binary. Regex exists in some heaven far, far above us where Javascript and PHP angels dance on clouds of non-memory-managed code and you can do things like:

var a = 5;
a = "Now I'm a string!";

We do things the hard way in C. But that's why we're like 9,000 times faster ;)

**Comment by bdkjones** [comment]
That last comment was my way of saying, "Dammit, I have no idea why that's happening."

**Comment by lstebner** [comment]
haha, I intended on getting you a project that shows this, but it's been a very busy week so far. I suppose there's no reason to import a blank file anyways, huh? :D

**Comment by bdkjones** [comment]
Actually, wait, does the APP show that main.less is connected to all the other files?

That is, are one.less, two.less, three.less, four.less ALL visible in the "imports" table view when you select "main.less"? Because if so, MY import scanning algorithm isn't broken! Then, this issue becomes one for the less compiler itself. That would explain why I can't find anything that would cause this behavior.

**Comment by lstebner** [comment]
yeah, the APP still shows the file as being imported

**Comment by bdkjones** [comment]
Huzzah, I didn't screw up. 

This is an issue for Less.js itself at this point; the app simply passes the files to the less compiler (less.js), and it would seem that the app is correctly linking imported files even when one of them is blank. 

Please file a bug with less.js. And give Alexis a hard time. ;)

**Comment by badlydrawnrob** [comment]
I only just found this one out. Took freakin' ages to figure out ... bummer.
