### ISSUE TITLE
Items not centered in JS sidebar

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#114]
http://dl.dropbox.com/u/1396727/sidebar.png

**Comment by bdkjones** [comment]
Damn. Is this consistently reproducible? Does it happen only on the Javascript inspector pane, or on other panes as well?

**Comment by paulyoung** [comment]
It was consistently reproducible when I logged the issue, but not today. Only on the JS pane.

The text still looks off center.

http://dl.dropbox.com/u/1396727/jspane.png

**Comment by bdkjones** [comment]
I believe the issue here is that if you resize the inspector while your computer is REALLY maxed out, OS X doesn't draw the view correctly and the bounds are permanently screwed until you restart the app.

Not sure what I can do about that, although I do plan to optimize drawing down the road (premature optimization = root of all evil and so on.) It's pretty dang fast right now, but I'm sure I could tweek it a little.

I can't reproduce this issue on my end.

Also, the text is not centered in the screenshot above, but the LINE (including the checkbox) is.

**Comment by paulyoung** [comment]
Just realized - pretty sure I was also using a LED Cinema Display to extend my desktop at the time.
