### ISSUE TITLE
Renaming to change CSS compiler

### ISSUE THREAD

**Issue by webster** [bdkjones/CodeKit-1-Old#122]
If I rename 'style.scss' to 'style.less' intending to switch from SCSS to Less, CodeKit recognizes the file path has changed, but continues attempting to process it as SCSS.  I'd expect to either be prompted, given the option to change, or it automatically changing.  The solution was to completely remove the project and add it back again.

**Comment by bdkjones** [comment]
Yea... SCSS and Less are not interchangeable (as far as I know). The two languages use different syntaxes, so simply renaming a SCSS file to a LESS file isn't going to make it work. 

Because of the above, I did not anticipate anyone doing this. That's why the app doesn't support it. Still, it may be worth catching.

**Comment by webster** [comment]
I had created a file planning on using SCSS but switched to Less (before writing anything that wouldn't have been supported by Less), which is what happened.

**Comment by bdkjones** [comment]
Fixed in 4115.

Changing the type of file will now result in the "old" file being automatically removed from CodeKit and the new file appearing with the default settings.
