### ISSUE TITLE
Feature Request: Embed images as data URLs

### ISSUE THREAD

**Issue by skid** [bdkjones/CodeKit-1-Old#140]
This is a very useful thing to add to CodeKit (I do it with a script over my compiled CSS files):

You can read the images from the stylesheet, base64-encode them and inline them as data url's. The application will decide which images to inline based on a setting. For example:

Embed images smaller than X Kb with extension Y that match/don't match the following regex ...

**Comment by ghost** [comment]
I was searching for this feature as well.

**Comment by bdkjones** [comment]
Yea. Ideally, I'd like to see this added to the language compilers themselves: Less, Sass and Stylus. 

The reason is that, otherwise, CodeKit would be forced to make TWO sweeps over the file each time it processed it. First, to compile it to CSS, then to scan the CSS and base64 encode the images. This would dramatically slow down the response times.

Have you opened this issue on the respective GitHub pages for Less, Sass and Stylus? I'm sure there are a lot of people that would like it and if they implemented it at that level, we could do it with virtually no slow-down in compile times.
