### ISSUE TITLE
Watch Ignore?

### ISSUE THREAD

**Issue by brajeshwar** [bdkjones/CodeKit-1-Old#148]
I use Compass, and a config file to do my SASS compilation. Is there a way I can either ignore files to watch in CodeKit or allow CodeKit to respect the Compass config file?

**Comment by bdkjones** [comment]
Yea... I realized this shortcoming just yesterday.

It is currently possible to do this, you just have to right-click the file in CodeKit and choose "Set to not directly compile" from the menu. But you can't _unignore_ a Compass file that you set to ignore. As such, I've implemented a full Inspector for Compass files, so that you can easily set them to ignore/unignore. It'll be in the next beta release which should go live in a few days.

Thanks for pointing this out!

**Comment by brajeshwar** [comment]
Thanks. Will look forward to the new beta release.
