### ISSUE TITLE
[BUG] Changing JS filename doesn't update output filename

### ISSUE THREAD

**Issue by simonhamp** [bdkjones/CodeKit-1-Old#149]
One of my guys had an issue when changing the filename of a javascript file that imports a couple of other files and outputs a minified version in the same folder... it didn't update the output filename when refreshing the project files. We had to remove the project and reinitialise it, which has sorted the issue, but that's not ideal.

I hope it's not too much of a pain to fix. Let me know if you need any more input :)

**Comment by bdkjones** [comment]
This was actually a deliberate decision on my part. Here's what I was thinking:

1) I have a file named "myScript.js"

2) I use CodeKit to minify this file, and it gets written to "myScript-min.js"

3) I now go to all my HTML files and add a script tag to the HEAD element that references "myScript-min.js"

---

4) I now rename "myScript.js" to "carolina.js"

5) If CodeKit automatically changed the output location, it would write that script to "carolina-min.js". But that would break my entire website, because I'd have to go update the script tags in the HEAD elements to point to the new output file. Worse, the original "myScript-min.js" file still exists, so as I madly refresh my browser wondering why the hell it's not showing the changes I made to my script, I will get increasingly more angry. 

---

So, the way I handled this is to "lock" the output file path until you change it manually. That way, you KNOW you have to go update all your HEAD elements to point to the new script. The other way, you MIGHT figure that out after a lot of cursing and general throwing of things.

**Comment by bdkjones** [comment]
Or are you saying that your guy renamed the OUTPUT file (myScript-min.js) in the Finder and CodeKit didn't change that in the app?

If THAT'S the case, again I had a good reason: you could theoretically work-around the required suffix this way. 

1) Compile "myScript.js" into "myScript-min.js"

2) Go to the finder and rename the output file from "myScript-min.js" to "myScript.js", assuming it's in a different folder.

3) Massive opportunity now exists for CodeKit to overwrite the wrong file, destroying your work. (You'd have to shuffle some files around and take a series of rare steps for this to happen, but it's possible.)

That violates CodeKit's prime directive: _never destroy source files_

**Comment by greystate** [comment]
@bdkjones Though I'd probably have reported this issue myself (if I'd encountered it), I very much like the reasons you state for _not_ changing the output path once locked. I'd vote for keeping it this way.

**Comment by simonhamp** [comment]
@bdkjones No my guy didn't change the name of the output file. Just the name of the origin file

I think those are completely valid reasons and I agree - good design choice.

How do you change the output filename though once you've changed all of the references to it? If we change it manually in the file system, will CodeKit pick up the change and start processing into the new min file?

What if this is part of a larger refactoring that dynamically calls the expected minified file, only to find that it hasn't been generated? Would be nice to at least have the option in our case to always generate the file based on the latest source file's name.
