### ISSUE TITLE
excluding folders in  hidden folders'  preference doesn't seem to work on initial scan.

### ISSUE THREAD

**Issue by bob-van-der-bibs** [bdkjones/CodeKit-1-Old#152]
excluding folders in  hidden folders'  preference doesn't seem to work for initial scan.

I've added the folder 'core' which usualy has the CMS in it  to the 'hidden folders & files' list and the 'auto ignored items'.
but still codekit tries to scan them on initially adding the project folder. resulting in an 'Maximum item Limit exceeded'

**Comment by bdkjones** [comment]
Yep. This is the expected behavior.

The "hide" feature doesn't actually stop CodeKit from watching the files/folders in question. It just prevents them from showing in the UI and processing when you change them.

Fortunately, I've removed the auto-ignore and auto-hide tables and replaced them with a new "skipped items" table in the next build. You can add items by filename (somefile.js) folder name (somefolder) or extension (*.js). CodeKit will completely skip all items that match your criteria, so they won't count against the 10,000 file limit.
