### ISSUE TITLE
Frameworks Should Include CSS Files - Not Just LESS Files

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit-1-Old#156]
New user to CodeKit so I apologize if this feature request is already in the product and I'm missing it.

I am setting up some frameworks and more than a few of them contain CSS files that I want to include in my own projects.  When I set up the framework, however, it does not recognize CSS files - only LESS files.  Could I just change all the CSS files to LESS files in my frameworks?  Sure...but here's why that's a problem:  I have a ton of frameworks that I pull down from Github to get the latest versions/fixes and I don't want to have to change the file extension every time I do this.  Here's what I'm looking to do:

1)  Find a cool project on Github with useful CSS and whatever in it.
2)  Clone down project to my machine.
3)  Set up framework in CodeKit that references this project.
4)  Include needed CSS files into my own projects using CodeKit via the @import "coolFile.css"; directive.
5)  Occasionally do a pull from Github to get any changes / fixes to the referenced file(s).

Does that make sense?  From what I can tell this is not possible right now as CodeKit only recognizes LESS files in frameworks.  If it could recognize CSS files in frameworks and import those files into project LESS files via the @import directive it would be great.

**Comment by ghost** [comment]
By the way...been using CodeKit for a week or so and just wanted to say it kicks absolute ass...keep up the good work.  You'll get my $10 when it goes on the app store.

**Comment by danielredwood** [comment]
Completely agree... Would also be rad if changes in the CSS file auto-refreshed the page (same as HTML).

This app rocks the lobster so hard.

**Comment by bdkjones** [comment]
Yea... I see the point here. 

I'm not ruling this out, but I have a pretty solid "Use a freaking modern stylesheet language" rule. The other issue is that adding CSS files clutters up the UI needlessly (you'd see a target file after ever LESS, SASS, Stylus file) and it takes up more of the 10,000 file limit that OS X places on every app.

I might add this at some point. But there is a complication: Less, Sass and Stylus don't attempt to process CSS import statements. They just spit them out into the compiled output, as is. An import statement to a LESS file gets replaced with the contents of that file. An import statement to a CSS file just gets written to the compiled CSS file. Which means that the framework path is not automatically resolved --- CodeKit would need to resolve the path, then change the text of the import statement. This is certainly doable; it just takes some careful coding.

Until then, as a workaround, you might write a little Applescript that goes through a folder and renames every file from *.css to *.less. Then, you could do your Github pull and just run the script to get the files renamed.

**Comment by richardp-au** [comment]
It would be nice to have the option to have Codekit embed CSS content into the Less files (perhaps with a preference to determine if they're embedded before or after Less processing). This would be good because not only can you combine stylesheets, but it becomes easy to minify them too.

One problem I found with renaming .css to .less is that it the Less parser breaks on jQuery UI due to an IE hack (display/**/: block;). I'd happy remove this line because it's for IE5 support but it's an extra manual step every time I download a new version of the CSS. If Codekit could simply embed this CSS file after Less processing, and then minify the output, I'd be happy!

**Comment by bdkjones** [comment]
Oy, the heuristics involved in doing that are super complex.

What if the CSS you want to embed after LESS is through compiling has a selector that overwrites one that the LESS compiler created? Where should the embedded CSS be placed --- it won't necessarily appear where you think it will, because the structure of a LESS file is greatly changed when it's compiled (mixins expand, etc.) And this could lead to some really nasty, hard-to-debug bugs in your code.

I can see adding support for CSS framework files, but trying to actually write CSS to the compiled file is probably out.

**Comment by richardp-au** [comment]
Sorry, I wasn't considering the option of importing CSS anywhere. I was merely thinking about importing at the start or end of the file.

Based on that, you could simplify the concept a lot by adopting the same @codekit-prepend and @codekit-append directives you use for JavaScript. It's then up to the user to ensure they aren't overwriting their selectors.

**Comment by bdkjones** [comment]
I've thought about this more. I'm going to stick to the "CodeKit doesn't do anything with CSS files" line for now. I think that's going to have to change down the road, as CSS4 comes online and the W3C obviates Less, Sass and Stylus by building their features into the language. But for right now, I really want to keep the app clean and simple and focused on smart stylesheet languages.

**Comment by ghost** [comment]
Understandable.  Still a great product and looking forward to official release.
