### ISSUE TITLE
Source JS file randomly appears 'missing'

### ISSUE THREAD

**Issue by Gidgidonihah** [bdkjones/CodeKit-1-Old#158]
I can't pin down when or why this is happening, but every once in a while, when I save my js file, I wait for the growl notification to appear saying it compiled, but it never comes. When I go to look at the codekit window, the file appears to be missing. The file isn't actually missing, it's still in the correct location, but codekit can't seem to see it. Restarting codekit does nothing. The only way I can get it back is by deleting the file from codekit and refreshing, which is a bit of a pain due to having to re-add the appended files.

If it helps, the file is on a network (smb) drive. I am editing the file via macvim on the network share. There are about 9 files that get appended to the js on compile.

**Comment by bdkjones** [comment]
Hmm.. I'm gonna guess that the network drive has something to do with this.

Does it happen ONLY for Javascript files, or does the same thing happen to other files as well? Is another person accessing the same file at the same time and saving it, or are you the only one with an open copy?

**Comment by Gidgidonihah** [comment]
I've only noticed it happening with JS, but I'm editing the JS file far more than anything else.
I am the only person with access to the file.

**Comment by bdkjones** [comment]
What editor are you using to save the file?

**Comment by Gidgidonihah** [comment]
Macvim

**Comment by bdkjones** [comment]
Can you try saving the file with another editor? (Textmate, Coda, Espresso, Xcode, etc)

I believe the issue is that BBEdit and MacVim are doing non-atomic saves whereas other editors do atomic saves.

**Comment by Gidgidonihah** [comment]
Changing text editor, now that's a tall order. It happens inconsistently so I'll have to switch for a while. I'll let you know if I find anything.

**Comment by bdkjones** [comment]
Is this still going on?

**Comment by Gidgidonihah** [comment]
Yeah, but I haven't been able to narrow anything down.

**Comment by bdkjones** [comment]
What's going on, I believe, is this:

CodeKit uses file descriptors to decide whether a given file is the same. This means that if you have a file in a project called "test.js" and you delete it, then create a NEW file called "test.js", you'll see both in the app. This is because while the new file has the same name as the old one, it has a different file descriptor (because it is, really, a different file.)

So something you're doing is essentially replacing the file with a new one, changing the file descriptor and causing CodeKit to see the old file as missing. Have you looked at the Help page on incident57.com/codekit and followed the directions for MacVim?

**Comment by Gidgidonihah** [comment]
If this is the case, wouldn't a NEW js file show up in the list when codekit thinks it has gone missing? As it is, test.js disappears, and won't show up again until I remove the "missing" test.js.

If disabling the swap and backup features of vim is the only solution, I suppose it will just have to be a PITA I live with.
