### ISSUE TITLE
SASS imports wrapped in some media queries not detected

### ISSUE THREAD

**Issue by andrewrocco** [bdkjones/CodeKit-1-Old#166]
Say we have our main compiled stylesheet, base.scss.

The only contents of base.scss are the following lines:

``` css

@import "mixins";
@import "reset";
@import "grid";

@media (min-width:300px) { @import "300"; }
@media (min-width:480px) { @import "480"; }
@media (min-width:600px) { @import "600"; }
@media (min-width:768px) { @import "768"; }
@media (min-width:992px) { @import "992"; }

@media only screen and (-webkit-min-device-pixel-ratio: 1.5),
       only screen and (-o-min-device-pixel-ratio: 3/2),
       only screen and (min-device-pixel-ratio: 1.5) { @import "2x"; }

```

In this case, only mixins, reset, grid, and 2x are detected as being imported by the inspector. 300, 480, 600, 768, and 992 are not in the "Imports:" list when base.scss is selected in the Codekit styles list.

**Comment by bdkjones** [comment]
First, I assume that 300, 480, 600, etc are actual files that exist in the same folder as base.scss.

If that's true, try rewriting the @media lines like this:

```
@media (min-width:300px) {
    @import "300";
}
```

The algorithm that scans files for import statements may be ignoring the @import statements because they are on the same line as the @media statements. If this is the case, moving the @imports to a separate line should make them work. I'll then tune the algorithm so that the single-line variety works as well.

**Comment by bdkjones** [comment]
The other problem with this code, however, is that CodeKit has no way to resolve the conditional statement associated with each @media() declaration. "min-width" is completely meaningless until the code is actually executed in the browser.

Which made me realize: those imports (300, 480, 600, etc) must be CSS files, not SCSS or SASS files, right? In other words, that whole block of @media queries is supposed to be carried through to the compiled base.css file just as it is. Then, when the browser parses base.css it evaluates the conditionals in the media queries and brings in the right css file (300, 480, etc.)

If this is the case, the @import algorithm in CodeKit is seeing the import statements just fine. The issue is that CodeKit does not watch or handle CSS files. So it does not establish links to them in the tableView in the inspector. And, consequently, when you make a change to one of those CSS files, the app does not recompile base.scss.

But this is fine, as making a change to one of those CSS files has no effect on the contents of base.scss anyway.

**Comment by andrewrocco** [comment]
Reformatting the @ media lines to fixed the issue. Thanks!

But, in this specific case, the imports (300, 480, etc) are actually SASS files. I am not importing any .css files in my project.

**Comment by bdkjones** [comment]
Okay, I've tweaked the parser so that it now handles multiple statements beginning with @ on the same line.

It'll be in the next beta. Until then, the multi-line workaround will get you through.

**Comment by andrewrocco** [comment]
I appreciate the quick response.

Been using CodeKit for production work for the past couple weeks. Love it! Thanks for an awesome tool.
