### ISSUE TITLE
Feature Request: Compass Frameworks

### ISSUE THREAD

**Issue by pyronaur** [bdkjones/CodeKit-1-Old#174]
I would really like to be able to include Frameworks AND have Compass. For example I like using normalize, which Compass doesn't have, and I have my own mixins that I like.

A quick and dirty milestone fix for this would be to at least allow Drag & Drop copying files. So I could at least drag&drop the files that I want from my Framework, onto my Compass project, and as a result I'd get them copied over. At least this way it wouldn't bee so hard to do, would it ?

**Comment by bdkjones** [comment]
The problem is that there is currently no way to tell Compass, "Hey, I know you're not going to find 'style.sass' in the spot where that @import statement says it should be. When that happens, look for it in this folder, X, instead."

The other compilers (Less, Sass, and Stylus) all have this functionality and it's what underlies the Frameworks concept. The only thing I could do is have CodeKit copy a framework file to the location in your project where it needs to be in order to match the @import statement in the file. But this defeats the whole purpose of frameworks, which is "one copy of the file."

So, I haven't artificially disabled Frameworks for Compass projects --- it's a limitation of Compass itself.

**Comment by bdkjones** [comment]
Note: I've already discussed this with the Compass guys. If they add support in a future release, CodeKit will adapt to allow Frameworks + Compass.

**Comment by pyronaur** [comment]
It does defeat the purpose to have one file, but it still offers me to have organized library, and if I can't have one file, then at least I can have my mothership somewhere, and import/overwrite when I make changes. 
Besides, such feature could be very useful, when (for example) sending the files to another developer, as he/she will need the linked files anyway - so a way to copy files from the mothership is necessary anyway.
