### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by msaspence** [bdkjones/CodeKit-1-Old#175]
When trying to compile a project which is a scss folder with 4 scss files in I get:

Compass was unable to compile one or more files in the project: 

Errno::EACCES on line 243 of /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb: Permission denied - ../css
Run with --trace to see the full backtrace

I have access to the scss and css directories

**Comment by bdkjones** [comment]
Are you running any Compass plugins/extensions in this project?

**Comment by msaspence** [comment]
Nope, just pulling in sencha touch scss from another directory

**Comment by msaspence** [comment]
Sencha touch stuff is a compass framework, dont know if that counts as a plugin/extension?
But that seems to be added ok as if I do some thing to screw that up (like add the project the level up, without the config.rb that adds sencha framework) then I get "Syntax error: File to import not found or unreadable: sencha-touch/default/all"
So I'm guessing if it can't find the framework it fails there and if it can it fails when it tries to write to css?
Kinda of guessing here, but just trying to add as much helpful info as possible.

**Comment by bdkjones** [comment]
Yea, the issue is that Compass can't write to the CSS folder.

1) Are you sure the output path is set correctly? I believe that error message above should supply a full path to the CSS folder, which we'd expect to be something like: "/Users/You/Documents/Clients/Project/css" (At least it seems that way to me; I've never seen this error before.) 

2) Are you sure you have WRITE permission for the CSS folder? 

3) Delete the CSS folder and recompile the project.

4) Create a new project from scratch, set it up the same way and see if you can duplicate the problem.

**Comment by msaspence** [comment]
1) This worked and I used File.dirname(**FILE**) to make it work from any location

However it now feels the need to open /Applications/Safari/Contents/Resources in finder, which I guess is a separate issue and not related?

**Comment by bdkjones** [comment]
Huh. Never seen that before. 

What version of OS X are you running? Which build of CodeKit? What other apps are open on your system? When does it open that folder in the Finder?

**Comment by msaspence** [comment]
It looks like it was something to do with refreshing safari tab
Disabling and enabling auto reload for safari has fixed it
