### ISSUE TITLE
Missing "use strict" statement.

### ISSUE THREAD

**Issue by kinoli** [bdkjones/CodeKit-1-Old#176]
Hi, I'm using JSHint to syntax checking and I have strict unchecked and globalstrict  checked in my syntax Lints preferences but I am still getting this silly ecmascript 5 error of 'Missing "use string" statement' when compiling. Is there any way around this error? It makes syntax checking pretty much useless for me if I can't get around this.

It is erring out on my first line here...

```
$('#main_nav li').each(function(i) {
    $(this).addClass('theme_'+i);
});
```

Thanks.

**Comment by bdkjones** [comment]
I'm afraid I can't give you an answer --- I just implement jsHint and jsLint. I'm not sure which exact settings you need to check in order to override this warning. I would recommend asking Anton (the guy behind jsHint): https://twitter.com/#!/valueof

But since this is not a CodeKit bug, I'm closing the issue. Good luck!
