### ISSUE TITLE
Only recognizing last line in Sass file for imports

### ISSUE THREAD

**Issue by postpostmodern** [bdkjones/CodeKit-1-Old#177]
When I have a Sass file that includes multiple `@import` lines, the only one recognized by CodeKit is the last line of the file. 

For example, if  **styles.sass** looks like this:

``` sass
@import vendor/pie
@import vendor/html5boilerplate
@import vendor/formtastic
@import theme/colors
@import theme/fonts
@import theme/buttons
@import theme/global
@import theme/layout
@import theme/forms
```

CodeKit will only show ___forms.sass__ in the **Imports** for **styles.sass**, and only ___forms.sass__ shows **styles.sass** in the **Imported By** box.

Of course, the Sass processor works just fine and imports all of them, but since CodeKit only recognizes the last file, it does not recompile when any of the other files are saved. I also tested this with a Sass file that imported only two very simple Sass files, and observed the same result. And if I have an empty line at the end of the file (after the `@import` lines), CodeKit will not recognize any imports at all.

**Comment by bdkjones** [comment]
Okay.

I've fixed this issue and should have a new build posted in a couple days that includes it. The problem is that the parser was including the final \n character on each line in the filename. So instead of looking for "vender/pie.sass" the app was looking for "vender/pie\n.sass"

Either way, the fix will be live in a couple days. (Just finishing up some stuff for the next beta build.)
