### ISSUE TITLE
Feature Request: Gif format support.

### ISSUE THREAD

**Issue by norhythm** [bdkjones/CodeKit-1-Old#178]
Mostly developers are using gif as lightweight image and animation.
Course me too.
I hope gif format support.

**Comment by bdkjones** [comment]
The reason is that most gifs are already only a few bytes in size. The gains to be had by optimizing them are very, very slight. And, with CSS3 gaining widespread adoption, many of the traditional uses for gifs (gradients, backgrounds, etc) are disappearing.

I haven't ruled out adding gif optimization to the app; it's just not a very pressing need for most devs.

**Comment by norhythm** [comment]
OK. I see.
CodeKit is very convenient also as a filer. 
I'm glad when a gif formt is also displayed. Of course, you do not need to optimize.

Thanks!
