### ISSUE TITLE
Concatenating order - JS, LESS and SCSS

### ISSUE THREAD

**Issue by jaggli** [bdkjones/CodeKit-1-Old#183]
While concatenating javascript files by append/prepend or importing less/scss files with @import, CodeKit doesn't respect the append/prepend order. Instead the files are ordered by adding date. I know about ordering by hand in the include-list, but this won't solve my problem, because of project sharing with co-workers.

My suggestion for JS: 
1. every prepended file in the order of all @codekit-prepend, 
2. every appended file in the order of all @codekit-append.

Suggestion for LESS/SCSS:
include the .less/.scss files as they are listed

**Comment by bdkjones** [comment]
Yea. I've known about this issue since August. It only manifests in this instance:

You have a file with existing import statements. Say:

```
@codekit-prepend "one.js";
@codekit-prepend "two.js";
```

Then you come along and add an import statement. If you add it to the END of the list, everything is kosher. But if you add it anywhere else (the middle or beginning of the list), CodeKit will still tack the import onto the end of the list in the UI.

This was not originally a big deal. Back when I wrote the code, CodeKit didn't provide the ability to import javascript/coffeescript files. And since Less, Sass and Stylus compilers handle order on their own, it didn't matter what order the files were listed in the CodeKit UI; they were still compiled in the correct order. 

But, when I added the JS/CS import features, this was no longer acceptable. I put off re-writing the import code because it is, imaginably, quite complex. You really don't see it until you sit down and try to handle all the situations that can happen:

Example: user adds import statement at position 3, deletes an import statement previously in position 5, changes the import type from "prepend" to "append" for the import link in position 0, and the file for the import statement in position 2 has gone missing. Figure out the new list!

So, I just let this issue slide for a while. I knew it needed to be fixed, however, so I've sat down and fixed it. I am now thoroughly testing the new import code so that I make sure I didn't screw it up. The fix will be in Beta 9.
