### ISSUE TITLE
Safari auto-reload doesn't work

### ISSUE THREAD

**Issue by fabiozc** [bdkjones/CodeKit-1-Old#191]
I've set up auto-reload to Safari when I save the Less file (The active tab in the frontmost window). But, Safari's  tab is reloaded and nothing is updated!

I dont know why, so.. I throw the ball to you! =)

Thanks!

Ps: Chrome is ok!

**Comment by bdkjones** [comment]
Hi fabiozc, 

Auto-refreshing got a massive update today with the release of beta 9. Please see if it resolves the issue.

**Comment by fabiozc** [comment]
thanks a lot!

i'll be on of firsts buyers when codekit leaves beta! Go on! =)

**Comment by bdkjones** [comment]
Is this issue fixed?

**Comment by fabiozc** [comment]
unfortenelly.. not at all!
now safari does not refresh neither before nor after.. nothing happens!
only when i change to safari and press CMD+R..

**Comment by fabiozc** [comment]
maybe because i'm testing on file:// protocol
when the open tab is http, the pages refresh (but i did'nt test with less file yet)

**Comment by bdkjones** [comment]
Yea, the file:// won't work. If you want to use file://, then you've got to turn off "injection-reloading" in the preferences.

**Comment by fabiozc** [comment]
The same issue than before the update.. the pages refreshes, but the css still the same, i need to refresh manually

**Comment by bdkjones** [comment]
Can you send me the project you're working on so that I can debug?

**Comment by fabiozc** [comment]
sure!
-- URL REMOVED --

open the single html file and /css/less/how-works.less
simple change on line 15 font size to test

PS: after download file, please, remove link. Thanks

**Comment by bdkjones** [comment]
It works perfectly over here in Safari and Chrome.

I think what's happening is that you don't have the output path set correctly in CodeKit. Unless you've changed the preferences for default output paths, when you add the project to CodeKit, it sets the following output path on your "how-works.less" file:

```
/css/css/how-works.css
```

But in the page, you've got the following tag to include the CSS:

```
<link href="css/how-works.css" media="all, screen" rel="stylesheet" type="text/css" />
```

Which means that the browser is looking for the CSS file in this location, relative to the project folder: /css/how-works.css
 But the one that CodeKit is compiling, unless you've changed the default output path, is appearing here: /css/css/how-works.css

This is because CodeKit is set, by default, to use this folder structure:

```
-- Stylesheets
     -- Less
     -- CSS
```

But you've got your project set up with this structure:

```
-- css
    -- less
```

Verify that you've got the output path set correctly in CodeKit and I think you'll find that the refreshing is working perfectly!

**Comment by fabiozc** [comment]
Yes, i've seted up correctly the path file, otherwise, the cmd+r it wouldnt work, right?

**Comment by bdkjones** [comment]
True, cmd+R would not have worked. But can you verify that the output path is set correctly since you upgraded to Beta 9 of the app? The default settings for output paths changed in the latest release, so while it may have worked in older versions of the app, unless you manually changed the output path after you added the project to Beta 9, it's compiling the CSS to the wrong location.

Put another way, can you change the font size on line 15 to, say, 75px, then save the LESS file, switch to your browser and hit refresh? If it doesn't show the change, then the output path is the problem.

**Comment by bdkjones** [comment]
Also, are you still using the file:// to preview the page in your browser? 

If so, switch to using MAMP.

**Comment by fabiozc** [comment]
At first time I've opened the Beta9, already change the output path to my way.

Yes, it is exactly what im doing, changing the font size on Less file and saving (using Panic Coda), Safari's reload but doesn't change anything. So, I go to safari and press refresh....... and.. guess what? The font size is changed!

**Comment by fabiozc** [comment]
Ok, i'll try localhost soon, i keep you updated.

**Comment by bdkjones** [comment]
Okay, got it:

It's the file:// issue. If I use that to preview your page in Safari and then go change the Less file, I see exactly the behavior you're describing, regardless of whether "injection" reloading is on or off.

I think, for right now, I'm just going to have to say that using "file://" urls is not supported. I need to do a little more research to see why it's not reloading. 

But, the excellent news is that if you use MAMP (which you should do anyway!), the live reloading is working perfectly on your project!

**Comment by fabiozc** [comment]
ahhaha ok! i use almost all the time, but in this case.. is just a mockup for a client.

Don't worry about file:// right now.. im here just to tell you this issue.. 

keep going! I cannot live without codekit anymore! =)
