### ISSUE TITLE
Feature request: detect *.min.js

### ISSUE THREAD

**Issue by flyingeek** [bdkjones/CodeKit-1-Old#205]
If I use vendor library, already minified, do not try to lint and minify them.

Example:
- main.js needs to prepend feature.js and a jquery plugin awesome.min.js

I want the result in a single file.

I wrote main.js and feature.js, so I want to lint/concatenate and minify them, but I did not write awesome.min.js so only append or prepend it even if I asked lint/concatenate/minitfy for main.js (for example based on the min.js extension)

**Comment by bdkjones** [comment]
Yea, the fundamental rule here is:

"If you're going to combine and minify Javascript files, make sure you start with un-minified ones."

So, for example, you would download the un-minified "development" version of jQuery instead of the "production" version, which is minified. Pretty much every public script is going to provide an un-minified version to go along with a minified one.

The reason for this is simple: the minification process obfuscates variable names and makes them shorter. So if you have three variables:

```
var something;
var somethingElse;
var somethingMore;
```

The minifier will turn those into:

```
var a, b, c;
```

It chooses the shortest variable names it can, starting with the letter A. But if you try to combine minified scripts that were minified separately, there's likely to be variable collision. That is, both scripts will have variables A, B, C and so on. Not everyone is careful enough with scope to avoid these collisions.

Therefore, enter the golden rule:

YOU MUST combine all javascript and minify it at the same time. Do not minify one file and then combine that with other files and minify the result again!

**Comment by flyingeek** [comment]
Ok understood, but then I still have problem with vendor scripts which will give lint error, that means than I must include in my page one vendor script and one personal script.

Vendor script= minify + concatenate without lint
Personal = lint + minify + concatenate

To reach the single script goal, I then should either:
- do not use lint on my personal scripts
- be able to setup the lint option on each included scripts

**Comment by bdkjones** [comment]
Make sure you're running the latest release. I added the ability to set lint options for each imported file over a month ago.

**Comment by flyingeek** [comment]
Ok found it.

I was trying to set the imported files check syntax select box to none instead of removing the show errors checkbox inside the list of imported files.
