### ISSUE TITLE
Js files get -ck in filename when minified

### ISSUE THREAD

**Issue by bjora857** [bdkjones/CodeKit-1-Old#210]
Maybe this is expected behavior. But is the "-ck"  really needed if the files are saved in separate folder?

**Comment by bdkjones** [comment]
This is an "err on the side of caution" thing. 

It's also an "apply a universal standard" thing. When you go to write a script tag in the head element of a page, you can simply ask yourself, "Is this script something that CodeKit compiles for me?" If the answer is yet, you throw a -ck on there. It also makes it more clear in the page itself, so that when you come back to it three months later after not looking at it for a while, the -ck immediately triggers your memory and you go, "Oh, right, this is a CodeKit thing."

If you did -min, that wouldn't trigger the same response.
