### ISSUE TITLE
Incorrect number of projects and frameworks displayed

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#22]
[This](http://db.tt/PKLWupn) occurred naturally for me when the auto refresh fired just before I compiled Less.

You can reproduce by hitting the refresh icon and then very quickly saving a file which compiles.

**Comment by bdkjones** [comment]
I'm guessing the app went crazy after this, no? The progress bar did not disappear, etc?

**Comment by paulyoung** [comment]
The app appears to working as normal even after reproducing the issue several times. The progress bar disappeared as expected.

**Comment by bdkjones** [comment]
Yea, this is still going to require a fix. 

During a refresh, CodeKit destroys a lot of information about each project: import relationships, which files create others, etc. All of that information is reconstructed during the refresh by examining the file system and reading, character by character, every supported file. So if you trigger a compile at _precisely_ the right instant, it's possible that the compile won't include the imports, because those relationships don't exist in the model at the instant you compiled and the app asked the model for that information.

This is a good example of the hidden complexity that most folks don't appreciate... if you rename or move a file in a project, that WHOLE project has to be refreshed because the the new filename might mean that we're now supposed to import this file into some other file, or it might have broken an import link, etc. It's not as simple as it seems on the surface; there's a whole web that has to be kept intact for the app to work.

The solution here, I think, is going to be to simply delay any compiles until after the refresh completes. There's no other way to ensure the integrity of the process. The downside to that is that if you have a gigantic project or MANY projects in the app, refreshes can take a few seconds, which would mean you wouldn't get an immediate compile-on-save.

But really, the only time you need a refresh is when you rename or add files to a project. So we can just bump up the default refresh interval from 2 minutes to 5 minutes and let folks manually refresh the app when needed. That should virtually eliminate the collisions between when a user saves a file to compile it and the app simultaneously refreshes.

**Comment by paulyoung** [comment]
Agreed, compiling should be delayed until after refreshing and vice-versa.

I think no matter what the refresh interval you're still open to having the issue. In my case I just happened to save right on the interval.

**Comment by bdkjones** [comment]
The above strategy is implemented in 3071, closing this bug.

Note: I'm not exactly sure if it's possible for the reverse problem to occur. That is, if a compiler is asking the model for information about a file and then a refresh triggers. All access to the model is synchronized on the main thread, so theoretically the refresh method should not begin until after the compiler is done requesting information and has dispatched a separate thread to do the actual compiling. 

We're talking a window of _nanoseconds_ here, so it's impossible to test. (You can't click the compile button 3 nanoseconds before a refresh starts, unless you're Clark Kent.) So, the theory will have to hold.

**Comment by paulyoung** [comment]
Just in case this is relevant - I ran compile all in a huge project which took a long time.

While less was apparently still compiling the auto refresh kicked in.

**Comment by bdkjones** [comment]
Should not matter.

The compilers run on separate threads and do not access the model after they are dispatched. (If you open Activity Monitor while compiling a HUGE project, depending on your machine setup, you'll see CodeKit fire off 80+ threads --- the glories of Grand Central Dispatch!)

Were there any unexpected results?

**Comment by paulyoung** [comment]
I don't think so but wanted to mention it in case you thought it was an issue.

**Comment by paulyoung** [comment]
Back to this - I did 'Compile All' which took a very long time and I'm pretty sure there were at least a couple of refreshes during that time.

When everything had compiled the message at the top read, "Refreshing projects and frameworks (2 of 1)" and the progress bar never stopped.

I was able to quit and relaunch where everything seems OK.
