### ISSUE TITLE
Imported files not triggering compile

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#23]
See this [screen recording](http://db.tt/st52gFn)

**Comment by bdkjones** [comment]
Can you try adding a bogus class to the bottom of the file? something like:

#element {
    margin-top: 0px;
}

See if doing that causes the compile to trigger correctly. I've run into issues before where LESSC doesn't compile files if they don't have any style declarations in them.

**Comment by paulyoung** [comment]
That didn't work.

I also double checked that the imported files should be available to CodeKit (not outside of the project)

**Comment by paulyoung** [comment]
I just tried adding that imported file as a separate project and now it triggers the file to compile.

Other imported files however (some in the same project and directory as the file I'm compiling) still don't trigger it.

I'll try and create a demo project to reproduce.

**Comment by bdkjones** [comment]
Have you verified that the ignore checkbox is set correctly for each file? If X imports Y and you change Y, X will only recompile if it is set to in the app.

**Comment by paulyoung** [comment]
The folder containing the imported file was set as hidden via the General tab in preferences. When I removed the folder name and re-added the projects, saving the imported file triggered the desired file to compile.

**Comment by paulyoung** [comment]
To confirm, I added the folder name back as a hidden folder via preferences and re-added the project. Saving the imported file now does not trigger the desired file to compile.

**Comment by bdkjones** [comment]
Fixed in 3071. 

For reference, when you save a hidden or ignored file, the app walks the "imported by" chain starting from that file and checks each file in that chain to see if it's also hidden and/or ignored. If it finds a file that is NOT ignored and NOT hidden, it compiles that file and, if it hasn't reached the end of the "imported by" chain, it keeps going. 

This process repeats for every branch of the "imported by" chain. So if you change hidden file X that is imported by files Y and Z (and the latter two files are not hidden or ignored), both Y and Z are compiled. If Z is, in turn, imported by file A and file A is not ignored/hidden, file A recompiles, and so on.
