### ISSUE TITLE
Can't access OS X menu bar when in full screen mode

### ISSUE THREAD

**Issue by nathanpitman** [bdkjones/CodeKit-1-Old#231]
I understand that CodeKit doesn't have an app menu bar as such but at present the fullscreen behaviour is pretty inconsistent with how other OS X apps work. Maybe the app should have a menu bar which replicates the menu bar icon options to help give the user a more expected user experience? :)

**Comment by TuckerWhitehouse** [comment]
I agree, when running it as a menu bar app, i'd expect fullscreen to work the same as if I'm running it as a dock app.

**Comment by bdkjones** [comment]
Can't do.

Apps that are running as status bar icons are prohibited from displaying a menubar. (It's in Apple's HIG and, more importantly, I don't believe it's even possible without seriously hacking Cocoa.)

There is, to my knowledge, no approved way to tell the WindowServer, "Hey, when this app goes full screen, add a menu bar. But then when it leaves full screen, get rid of the menu bar." To do it, I'd have to dip into private methods, which would mean instant rejection from the app store. 

The issue is that most apps that run as status bar items aren't meant to have windows. They are usually little helper apps. This also means that these apps would never enter a full screen mode, so the issue in this thread is usually irrelevant for status bar apps.

In this case, I'm afraid if you want to run the app from the status bar, you'll just have to settle for no menubar in full screen mode. However, I've been very careful to make sure all the functionality is still available, either from the status item menu or from the gear menu in the lower left corner. I believe the only missing command is "send feedback."
