### ISSUE TITLE
CSS files don't seem to be recognized as imports for LESS files

### ISSUE THREAD

**Issue by mkoistinen** [bdkjones/CodeKit-1-Old#24]
Title says it all, but, I have a CSS file that I'd like to include at the bottom of a LESS file as it is compiled.  I suppose I can rename the file as .less, but this isn't the LESS way.  It should be able to import css files too.

**Comment by bdkjones** [comment]
You can certainly import CSS files into LESS files; when the LESS file is compiled, it will properly pull in all the content from the CSS file and put it where your import statement was.

The app itself does not recognize CSS files because that opens a huge pandora's box of issues: which CSS files are created by LESS files? Which are simply independent files? If you set an output path wrong or you rename a LESS file that results in an auto-renamed output path, we could end up overwriting an "independent" CSS file with the compiled output from a LESS file... it's just a bag of hurt.

LESS is a strict superset of CSS, so renaming the file to .less is perfectly acceptable. This is not true of, say, SCSS or Stylus files, however.

My general policy is that coders should pick a language for a project and use that language. If you're going LESS, everything should be in LESS. This is why, for example, LESS files can't import Stylus files even though, technically, I could write the code to make that work.

**Comment by mkoistinen** [comment]
The CSS files, in particular, come from a jQuery plugin.  I'd rather not waste another HTTP connection to fetch the file independently, so I thought I would just append it to the bottom of my own CSS file (as output by LESS).

Its clearly easy enough for me to rename to *.less, but the point, to me, is to retain the exact filename so that if the plugin author should make an update, it will be clear which file is which.

I'm not entirely clear about the Pandora's Box here.  Its pretty standard that all source LESS files come from the 'less' folder, not the 'css' folder.  If I promise to place my source .css file into my less folder, wouldn't that close the proverbial Pandora's box?

**Comment by bdkjones** [comment]
Ah, I see.

Yea... I should show you the emails I get from people. Let's just say that not all web developers are equally intelligent. The app has to deal with tons of edge-case scenarios, and not everyone puts their LESS in one folder and their CSS in another, so we can't rely on that.

Still, I see the issue here and will work on finding a good solution.

**Comment by mkoistinen** [comment]
Awesome, thanks, man!

**Comment by paulyoung** [comment]
@mkoistinen when you compile the CSS gets imported and output to the .less file though right?

You're just saying that the app should show it as a project file / imported file but you never want to take any action on it?

**Comment by mkoistinen** [comment]
No, the file is ignored by CodeKit unless I change it to have a .less extension.  I wanted it to be @imported as a normal import, but it didn't happen when I did this:

@import "plugin.css"; // Doesn't work in CodeKit

but:

@import "plugin.less"; // Works fine

(Obviously, renaming the actual files appropriately each time).

**Comment by paulyoung** [comment]
Interesting. I would have thought that when CodeKit invokes the compiler, lessc would import the CSS file as expected.

**Comment by mkoistinen** [comment]
Can you reproduce this?

**Comment by paulyoung** [comment]
Using lessc from terminal gives the exact same behaviour as using CodeKit.

style.less

```
@import url('import.css');
@import url('import.less');

body {
    background: #000000;
}
```

import.css

```
a {
    color: #cc0000;
}
```

import.less

```
p {
    color: #ffffff;
}
```

Outputs style.css

```
@import url('import.css');
p {
    color: #ffffff;
}
body {
      background: #000000;
}
```

**Comment by mkoistinen** [comment]
Oops.  I just checked the lesscss.org site and it also says that the @import will be left _unprocessed_ if the file is .css.  My bad!

**Comment by paulyoung** [comment]
Still, is there a case for displaying .css files in the UI as project and / or imported files?

I'm not suggesting that CodeKit watch imported .css files / compile the less file that imports them when updated.

**Comment by mkoistinen** [comment]
There is a case, but then this becomes a feature request rather than a bug fix =)

**Comment by bdkjones** [comment]
The app doesn't display CSS files because there's nothing the app can do with CSS files. They would just clutter up the UI.

**Comment by sheck** [comment]
I know this is an old thread, but you can do this now with
`@import (less) "lib.css";`
