### ISSUE TITLE
Setting 'Then:' to 'Concatenate Files' continues to minify

### ISSUE THREAD

**Issue by mkoistinen** [bdkjones/CodeKit-1-Old#25]
Hi again!

I was attempting to do some debugging by allowing my output files be unminified by selecting my javascript file and changing the 'Then:' drop-down from 'Concatenate and Minify' to simply 'Concatenate files'.  The output is still getting minified.  Did I misunderstand something?

**Comment by mkoistinen** [comment]
Oh.  One more thing.  I would've expected the 'Minify' button to change to something else when I explicitly disable minification.  Perhaps just 'Process' all the time?

**Comment by bdkjones** [comment]
Regarding the second point: the selection boxes at the top apply to what happens when you save a file only. The minify button stays as it is because you can click it to manually concatenate and minify the full import chain.

The first issue: if you have a chain of files that import each other: X, Y, Z and you save Z, the app walks back up to the start of the chain (X) and uses the settings you've set for that file. It applies those settings to the whole chain. Then, if file Y is not ignored, it repeats the process starting from Y, using Y's settings, applying that to the whole chain below Y, and writing the result to Y's output path.

So, if Y and Z are set to NOT minify on save, but X IS set to minify, the resulting output will be minified when you save any of those.

So you need to verify settings on the BASE file. After doing that, is this still an issue?

**Comment by mkoistinen** [comment]
I affected the settings of the primary file -- the one which things are concatenated to.  I also tried just saving the file (rather then pushing the 'Minifiy' button), but the results were still minified.

I think it is confusing for users to have a button with concatenates & minifies if the settings are only to concatenate.  IMHO, the button should reflect the settings.

**Comment by bdkjones** [comment]
Bug Fixed in build 3212.

The issue was not with the settings of the file. Basically, if a file already existed at the output path where the minified file was SUPPOSED to go, had it minified correctly, the "debug" version wasn't overwriting that file.
