### ISSUE TITLE
Feature lost!

### ISSUE THREAD

**Issue by scruffian** [bdkjones/CodeKit-1-Old#267]
It used to be possible to run JS Lint on javascript files and then "do nothing". Now the files are always minified. It would be good if this feature reappeared!

**Comment by bdkjones** [comment]
Actually, the feature is not gone. 

If you have a JS file that imports no other files, you simple choose "concatenate imports" in the "then" field and, since there are no imports, nothing happens. 

If the file DOES have imports, then it's incredibly unlikely that you'd ever want to change it without creating the output file (with all the imports combined). Hence, I removed the "do nothing" menu item.
