### ISSUE TITLE
Project settings for Compile paths for Less being overridden by global settings 

### ISSUE THREAD

**Issue by tenfef** [bdkjones/CodeKit-1-Old#268]
When you set the compile paths for less on the project level, the global output path overrides it.

**Comment by simonhamp** [comment]
We're experiencing this issue too. It would also be nice to see a way to reapply new settings on existing project files.

It also seems that the exported project settings JSON file stores the exact details for each file as it was at the point of import rather than just the principle rules for the management of files... so even after changing settings and reimporting the project (with exported settings file in root directory) it doesn't apply the new settings to previously added files.

**Comment by jbravata** [comment]
I'm not sure if I should open a separate ticket for this, but the same is true of the JavaScript minification suffix: The project setting is overwritten by the global setting.  

Also agreeing with Simon: A way for new settings to take effect without having to restart CodeKit, whether that is automatic application or an apply button somewhere, would be great.

Build: 5987.

**Comment by bdkjones** [comment]
This should be fixed in the release build. As for applying the defaults to existing files... that feature is on my list, but it's more complicated than it appears at first blush.
