### ISSUE TITLE
CodeKit doesn't detect file changes made on another machine

### ISSUE THREAD

**Issue by soluml** [bdkjones/CodeKit-1-Old#298]
When doing personal development, I use Dropbox as my versioning/cloud backup tool and sometimes I'll edit  .scss files on my PC.  Those changes are not automatically compiled by CodeKit when Dropbox updates the file on my mac.  Not a big deal as I can always compile once I get back to my Mac, but it'd be great to leave my mac mini on at home and develop on any computer ala Dropbox.

**Comment by bdkjones** [comment]
Yea, it's not possible for CodeKit to watch what's happening when you're changing files from another machine.

This is because CodeKit relies on the OS X kernel for change notifications. Doing this allows the app to watch thousands of files and consume exactly zero CPU cycles in doing so --- CodeKit does not use any resources until it's notified of a change.

The alternative is "polling", where CodeKit would access a file every X seconds and see if its changed. This is how most other tools work. The downside is that if you're watching lots of files, you waste lots of CPU time needlessly checking for changes. 

Polling would allow CodeKit to see that file X has been changed from another machine, but the performance hit is not something I consider acceptable right now.
