### ISSUE TITLE
Can't drag and drop project folders with file extension

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#30]
See this [screen recording](http://db.tt/CNwMZeu). I'm trying to drag and drop folders named bless.js and less.js into CodeKit.

I can add them via the '+' icon.

**Comment by bdkjones** [comment]
Fixed in build 3254.

For posterity: folders with periods in their names are a bad idea. CodeKit was set to ignore them; other apps may not be so gracious.

**Comment by paulyoung** [comment]
I hear you. A lot of my GitHub clones are in that format.

**Comment by bdkjones** [comment]
As an example, take a folder that's named something like "folder.js" and then rename it to "Yadda"

You'll see that CodeKit still calls that item "Yadda.js", which you might think is a bug. It's not. Because if you open an info window on "Yadda" from the Finder, you'll see this in the "Name and Extension" box: "Yadda.js"

This is an example of why it's really, really bad practice to name things that aren't files with periods.

**Comment by paulyoung** [comment]
True. I was thinking more for things like something.tmbundle or something.sugar which are still folders but have some kind of extension.
