### ISSUE TITLE
Changing preferences has no effect on existing projects

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#37]
If I want to enable / disable JavaScript support or change my Less output style I need to re-add the project and set all my output paths again.

**Comment by bdkjones** [comment]
Yep.

This is intended behavior. The preferences are "defaults" which apply when you add a new project. They don't change existing projects.

**Comment by paulyoung** [comment]
Can I request some per-project settings for this kind of stuff?

I have a project that I've set up and JS was disabled but now there's no way to turn it back on.

Would be useful if I want JS support in one project and not another, or different Less output styles.

**Comment by bdkjones** [comment]
It wouldn't matter. 

The app needs to know how to set up files when it adds a new project. That's what the preferences are for. It would be pointless to offer a per-project version of, say, "outputStyle" for LESS files --- because once the project is added, outputStyle has already been set to the default from the app's preferences. So the only thing a per-project level setting would add is the ability to click a project, choose new defaults, and have those overwrite the defaults set on each file. But that's problematic: what if I carefully configured all my files by setting the outputStyle on some to X and on others to Y. 

Nah. Bad news. 

You can already set the output style on multiple files simultaneously by selecting them all and changing it once. Likewise, if you added a project without JS support turned on and now you want it, just flip that preference and then click the refresh button. 

The opposite action (automatically remove all JS files from the app when you turn OFF js support) is a bad idea, because what if you've spent significant amounts of time setting up import links? That would immediately be trashed. 

The JS option in the preferences window is for people who will NEVER want to use the JS features of the app. If you want those features in some projects but not others, then in the projects where you don't want to mess with JS files, you select them and hide them.

**Comment by paulyoung** [comment]
Got it.

**Comment by bdkjones** [comment]
I can see that the ability to disable JS support is causing some confusion. As such, I'll remove the preference and simply let CodeKit always add JS files. That makes life simpler: if you don't want to work with JS files in a given project, just select them all and hide 'em.

I will keep the flag in the plist so that advanced users can disable the feature if they desire.

**Comment by paulyoung** [comment]
Setting JS files to not compile directly is enough for me - it means that JS files aren't going to be processed if I work on them while CodeKit is running, but means I can make use of the app's JS features in the future.

One thing CodeKit has done for me is give me a nudge that I need to be up to date on my JS methods; CoffeeScript, uglify etc - I've been putting off implementing them for a while but now it seems so easy there's really no excuse!

**Comment by bdkjones** [comment]
Yea... 

I think the confusion here is that it's easy to read that Languages preference pane, see a checkbox that says, "Minify with Uglify.js" for CoffeeScript files and then uncheck that box and think, "Okay, now the app won't minify coffeeScript files."

That's not true. The app will simply set NEW coffeeScript files that you add from that point on to not minify. It makes no changes to existing files.

In other words, the languages preferences are simply the default values for all the stuff in the file inspector that shows up when you select a file. It's asking, "What do you want all that stuff set to by default when I add a new file?"

There is no "Universal" preference for how to handle files of type X --- the app handles files according to their individual settings. The only preferences are for specifying what those individual settings start out as.

Does that make sense?

**Comment by paulyoung** [comment]
It does. In the previous comment I meant setting them to not compile using the existing method either individually or by a selection.
