### ISSUE TITLE
Error while compiling .LESS File after Update to Mountain Lion

### ISSUE THREAD

**Issue by lukashillebrand** [bdkjones/CodeKit-1-Old#381]
I get this error when compiling .less files after the Mountain Lion Update. :-/

  http://cl.ly/image/201m2L383d05

**Comment by phabz** [comment]
i´ve got the same problem since the last update (OSX 10.7.4)

**Comment by bdkjones** [comment]
Please send me the file that's causing this issue.

**Comment by lukashillebrand** [comment]
This is the file, thanks for the quick answer - http://cl.ly/code/2p2q2s3z2S0g I´ve noticed that it causes this problem only in one project.

**Comment by lukashillebrand** [comment]
Any suggestions?

**Comment by bdkjones** [comment]
Yep. You have an unbalanced parenthesis somewhere in your code. Run a find on the "(" character and ensure that each one is properly matched with a ")" character. The new version of Less is more strict about enforcing this.

-Bryan

**Comment by phabz** [comment]
thx! I fixed those character issues... now it's compiling my less files well again :)

**Comment by lukashillebrand** [comment]
@bdkjones thanks! @phabz could you send/post me your parser file please, so I don´t have to search trough, thanks!

**Comment by phabz** [comment]
It had nothing to do with the parser file. There were some missing closing ")" characters in the .less file. Syntax errors like ".function_gradient_tb (darken(@color, 10%), lighten(@color, 10%);" caused the problem. The LESS parser seems to be stricter since the last update. I fixed all of those errors and it now works like a charm :)
