### ISSUE TITLE
Request: Javascript "compile to"

### ISSUE THREAD

**Issue by Lalem001** [bdkjones/CodeKit-1-Old#390]
Allow an individual script, that gets compiled by CodeKit, to specify the target location of the compiled file.

Example
//@codekit-compileTo "../"; 

or

//@codekit-target "../"; 

or

//@codekit-location "../";

**Comment by bdkjones** [comment]
I really want to try to avoid adding proprietary keywords. The only reason I use "@codekit-prepend" and "@codekit-append" is because Javascript does not have an "@import" keyword like Stylesheet languages do. 

Right now, the mental model is pretty simple: if you want to adjust the output location of a file, you go into CodeKit and do it there. If I added this capability, now you'd have two places to set output paths: 1) in CodeKit and 2) in the file. Which one would take precedence if the two were not the same? The user would be pretty pissed if he attempted to set an output path one way and found that the file still compiled to some other location because he forgot that 2 months ago he added a statement in the file that set the output path. Etc. 

There's a lot of problems associated with this idea.
