### ISSUE TITLE
Sprite Problem.

### ISSUE THREAD

**Issue by dragszymon** [bdkjones/CodeKit-1-Old#403]
When I create a new compass project i choose "Images" as my img folder.

When I import in sass file;
@import "global/*.png";       and than put        @include global-sprite("logo"); 
in CSS it gives me this path           background: url('/images/global-saa11b5ce2b.png')

When i import in sass file this way:
@import "../images/global/*.png";         it gives me that:
 background: url('/images/../images/global-s14b6898770.png')

both methods are wrong becouse good path is background: url('./images/global-s14b6898770.png')

**Comment by bdkjones** [comment]
I'm afraid I don't understand the post. Additionally, this sounds like a Compass problem rather than a CodeKit one --- CodeKit does not resolve the paths in your @import statements; that's done by the Compass compiler itself. 

Try asking for help on a Compass website; they may be able to tell you what's going on.
