### ISSUE TITLE
CodeKit becomes frontmost application even when opened with `open -ga CodeKit`

### ISSUE THREAD

**Issue by mklement0** [bdkjones/CodeKit-1-Old#406]
The `-g` option of the standard `open` utility is meant to launch an app without activating it (without making it the frontmost application).

However, `open -ga CodeKit`, when executed while CodeKit is NOT running, launches the app _and unexpectedly activates it_. By contrast, `open -ga TextEdit` behaves correctly.

If the targeted application is already running, `open -ga ...` should by design be a NOOP.
While CodeKit correctly does _not_ activate when already running at the time `open -ga CodeKit` is executed, its behavior is again different from TextEdit (which behaves correctly) in that scenario: while the state of TextEdit's windows doesn't change at all (as expected), CodeKit's main window becomes visible in front of windows from other non-active applications (though it fortunately doesn't obscure the frontmost application).

**Comment by bdkjones** [comment]
The reason for this is pretty technical. In order to support running CodeKit as both a Dock-based app and a Status Bar based app, the binary launches slightly differently than normal apps. 

Essentially, it _always_ launches as a background task with no visible UI and then, based on the user's preference for where the app should run, transforms itself into either a Status Bar app or a Dock app.

This is why the -g flag will fail. Fortunately, 0.000001% of users will ever even try opening the app from the command line. ;)

**Comment by mklement0** [comment]
I see. I'm flattered to hear that I'm such a rare creature. I do have thoughts on launching from the command line that may appeal to a bigger part of the herd, though (separate issue to come).
