### ISSUE TITLE
Feature request: Combining minified and non-minified JS files...

### ISSUE THREAD

**Issue by mhulse** [bdkjones/CodeKit-1-Old#408]
It would be pretty cool to be able to combine minified JS with non-minified JS, and have full control over how each file is treated before they are combined.

In other words, I have several minified plugins and several non-minified scripts. I don't feel comfortable just downloading the un-minified versions (of the minified plugins) and using CK to minify them (like the docs suggest)... Reasoning: Some scripts I work with have been minified and compressed using different minification options; I'd rather not do the work of minification if it's been done once already... Also, most plugins I'd never need to see the un-minified code.

Optimally, my end goal is to combine all JS files, but pick/choose which ones get minified (i.e. all non-minified scripts) using CK's built-in uglifyjs.

I might be missing something, and please correct me if I'm wrong, but it looks like it's all or nothing when it comes to minifying **and** combining JS?

Thanks for listening! :)

Cheers,
Micky

**Comment by bdkjones** [comment]
The reason we do it this way is that minifying can be a real nightmare if you don't do it properly. For example, if you have three javascript files and you minify each one separately and then simply concatenate them, you stand a good chance of shadowing variables --- since the minifer starts at "a" for each of the three files, there are now at least three variables named "a" in your combined script.

**Comment by mhulse** [comment]
Thanks for reply.
