### ISSUE TITLE
Feature Request: Minify plain css

### ISSUE THREAD

**Issue by apfelbox** [bdkjones/CodeKit-1-Old#413]
Currently it is not possible to directly minify `.css` files.

The current way to do it is: change file extension to `.scss`, compile+minify, change file extension back to `.css`. 

I think it would be very nice to minify plain css files, too.

**Comment by guill3m** [comment]
+1

**Comment by oomlaut** [comment]
+1

**Comment by erikwoods** [comment]
+1

**Comment by bdkjones** [comment]
Renaming the CSS file to *.less or *.scss IS the correct way to minify CSS. The reason is simple: you want to have access to the non-minified version; you don't want to overwrite your hand-written CSS file with the compressed version, which is very difficult to read.

Therefore, you rename the file and write 100% standard CSS, set the option to "compressed" and save. Boom: minified CSS and your original, organized CSS file still exists. Cheers!

**Comment by erikwoods** [comment]
I don't think the OP meant to say what it sounds like they're saying. I think the OP is just saying that they want to be able to use CodeKit with .css files and not be forced to use less or scss extensions.

Obviously, overwriting your source CSS with minified CSS wouldn't be all that smart or good.

I know it might sound silly since you can just write plain old CSS in a less or sass file, but I think the idea behind it is to not force us to use less or scss if they just want to minify plain old CSS.

**Comment by apfelbox** [comment]
The use case is simple: you have legacy applications, in which you cannot just rename the css file for every developer to `.scss`. But you obviously still want to minify it.

The problem with the name clashing is simple. If minifying css, just name it `.min.css` - just like javascripts, too (same problem there, but solved).
