### ISSUE TITLE
Issue with name of items in Projects

### ISSUE THREAD

**Issue by mkoistinen** [bdkjones/CodeKit-1-Old#42]
Not a bug, per se, but I have two sites with the same name (well, its the same customer, but one is their 'static' site, then other is their CMS-based version, they're stored in different places on my machine, but the customer name is the same for each's top-level directory name).

CodeKit seems to work fine with multiple 'Projects' with the same 'name' in the list, but us humans need more to go on.

Suggestions:
1. Allow users to change the default name that appears in the list;
2. Display the path to the project in subdued gray beside the 'name';
3. Display a tooltip with the full page to the project folder.

My preference is No. 1.

**Comment by bdkjones** [comment]
Okay, okay, okay...

I've resisted this for a long time because I wanted the app to stay in-sync with the names of folders on disk. But I seriously get like 5 emails a week from Less.app folks asking for the ability to rename projects. (Most of them are people who drag the "less" folder from each of their projects onto the app rather than the project's root folder --- which is incorrect.) 

Projects are rename-able as of build 3430. 

Bear in mind, however, that this means if you specify a custom name in the app and then go rename the folder on your disk, the app is no longer going to change the project's name to that new folder name, as it does if you don't specify a custom name. Caveat emptor, as it were.
