### ISSUE TITLE
Refreshing projects and frameworks causes a slight hang in scrolling

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#43]
The first time I noticed this I was already scrolling and there was a noticeable pause when the refresh started.

Second time I was just starting to scroll, the refresh started and no scrolling occurred for a few seconds (this was way more noticeable) and then I jumped to far down the page.

**Comment by bdkjones** [comment]
Yea... Unfortunately there's not a lot that can be done.

While you're seeing the "hang", CodeKit is accessing Core Data on the main thread. It has to do some work during refreshes on the main thread because Core Data is not thread safe. Once it completes that required work, it then spawns an entire copy of the model in a background thread (basically, duplicates everything) and does the really heavy work back there.

At some point, though, we have to bring that stuff back to the main thread and update the real model with the results. That can only be done on the main thread.

**Comment by paulyoung** [comment]
Cool. Only added since you asked for things of this type, not because it's a big deal.

**Comment by bdkjones** [comment]
Yea... I pull as much work off the main thread as possible, but there's some that's just unavoidable.

Ever notice how, when you import a new album into iTunes, that little window pops up and the whole app is unusable until the import finishes? Same deal. iTunes' main thread is busy doing data work.
