### ISSUE TITLE
No auto-compile after update

### ISSUE THREAD

**Issue by seanschroeder** [bdkjones/CodeKit-1-Old#440]
I just updated to the latest version of codekit and now my files won't compile automatically on change. I'm on OS 10.8.2.

**Comment by bdkjones** [comment]
Hi Sean,

This is the first and only report I've had of such an issue. Have you tried restarting your Mac? If that doesn't get things going, try resetting CodeKit by quitting the app and then re-launching it while holding down the shift key.

**Comment by seanschroeder** [comment]
Yeah, I'm sorry. Here's what I've tried:
- Removing project-specific settings
- Adding project-specific settings
- Restarting Code Kit
- Restarting my Mac
- Resetting Codekit via Holding Shift as you mentioned above

Now, I'm getting a compilation error: "FATAL ERROR: CALL_AND_RETRY2: Allocation Failed-Process out of memory"

Interestingly, it's only Less files so far. .js files auto-compile just fine.

**Comment by seanschroeder** [comment]
Update: I "reset" codekit again. It now appears to auto compile. Will test further and report back.

**Comment by seanschroeder** [comment]
Okay, it worked that one time...sort of. Doesn't appear to see @imports. Now I'm getting that out of memory error again. Is there a way to download the previous version?

**Comment by seanschroeder** [comment]
Update: I downloaded the previous various version and it works as expected. If you'd like some help in tracking these issues down in the latest version, let me know.

**Comment by bdkjones** [comment]
Well... thousands of people are using 1.3 and so far, this is the only report of this issue. That strongly suggests that there's something unique about your machine, configuration, or project code that is producing the problem.

Can you upload all the projects that are in the app when the behavior occurs so that I can test them over here?

**Comment by kuldar** [comment]
I'm experiencing similar problem. Started after the last update (1.3) It seems that if I make changes to a .scss file, Codekit complies it without a problem, but when I do changes to a partial that's been @imported to a .scss file, Codekit fails to recognize any change and I have to make a save in non-partial .scss file to force the Codekit to compile.

The same behavior happened for both of my computers - MacBook Pro and an iMac

Also when viewing the Codekit window, for some reason Codekit seems to be on endless looping of linking @imports and refreshing the project. 

http://kldr.co/Kky4

Edit: This is happening only when I enable project-level settings

**Comment by bdkjones** [comment]
Okay, a couple quick questions:

1) Do you have any Frameworks added to CodeKit?
2) Have you attempted to reset the app by quitting it and then relaunching it while holding the shift key? If not, try that.
3) If the problems persist after that, can you send me a small demo project that shows the issue so that I can debug with it over here?

**Comment by kuldar** [comment]
1) Other than Compass, no. And it was the same without Compass as well.
2) I did the reset and the effects were the same - no compiling when saving a partial file. Also when I'm using project-level settings, clicking on "Refresh selected project" makes it refresh endlessly.
3) Sure, sent you the small project I'm working on.

**Comment by bdkjones** [comment]
Ah. Okay. Yes. The @import statement can't be structured like this CodeKit:

```
@import 
    "normalize",
    "compass/css3",
        "base"
```

And so on. This is fine for the Compass compiler because it's a full tokenizer/lexer/parser. When CodeKit scans for @import statements in files, however, it does NOT fully tokenize the file (because that would be slower and would mean we're essentially duplicating the work that the Compass compiler is about to perform.)

For speed, CodeKit simply scans a file until it finds an '@' character. Then it pulls everything from that character to the next newline statement and attempts to resolve it as an import link. That's why none of the files above are linking correctly in CodeKit and, therefore, that's why if you change "base" (for example), CodeKit does not go recompile the file that imports base.

You can do one of two things:

1) Start each line with an @import statement
2) Put multiple files on a single line like this:

```
@import "normalize", "compass/css3", "base";
```

**Comment by bdkjones** [comment]
And to head off the inevitable question: "Why don't you just change it so that CodeKit looks at everything from an "@" character to a ";" character?"

Because not all the languages that CodeKit support use semicolons to mark the end of a statement. Sass files don't. Neither do Jade. So we can't rely on the semicolon being present.

**Comment by kuldar** [comment]
That fixed the compiling problem. For some reason Codekit still seems to go on an infinite reload when project-level settings are enabled, even after reseting Codekit. But since I can just use app-wide settings, that's not a problem for me currently.

Thanks!

**Comment by bdkjones** [comment]
Hmm, I can't get the infinite-reload issue to manifest on my machine with the project that you sent me. Can you narrow it down to the project that's causing the problem and then send that my way?

**Comment by seanschroeder** [comment]
Two's a pattern ; ) ...so here are the less files I am getting the issues with. I, too, am importing several different files. Let me know if you need anything else:

https://dl.dropbox.com/u/693812/codekit-mura-less.zip
