### ISSUE TITLE
Clean up codekit-config.json generation

### ISSUE THREAD

**Issue by adamnbowen** [bdkjones/CodeKit-1-Old#443]
Every time the codekit-config.json file gets regenerated, the changeset is filled with irrelevant changes.  It seems that each time the file is generated, the order of rules isn't preserved, so git is filled with line additions and deletions that are irrelevant to any actual changes.

Would it be possible to generate this file in a predictable manner?  I know it isn't intended to be read by humans, but if it is meant to be tracked in version control (is it?), then changes in the settings should have a 1-1 correspondence with changes in the config.  Certainly leaving the app open for 5 minutes, or restarting my computer shouldn't result in a config update.

You definitely have a killer app here—it'd be great if this minor issue could be resolved.

**Comment by bdkjones** [comment]
Unfortunately, this can't be changed. The reason CodeKit does this is because it's _much_ more performant. Simply re-writing the file each time is orders-of-magnitude quicker than trying to determine if anything has changed and then modifying the file. We're talking many full seconds of additional time in a refresh to do it that way.

**Comment by iangilman** [comment]
There must be some way to fix this! It's extremely annoying. It's got me rethinking whether I should have gotten my team on CodeKit in the first place… All those irrelevant changes have no place in our repository.

I would be okay with doing that check every refresh, even if it did take a few seconds… Maybe give me a preference to turn it on?

Either that, or write the file out every time but do it in a predictable fashion, so it always goes in the same order and therefore creates the same structure if there have been no changes. It seems like the bulk of the changes I'm seeing are just chunks swapping places with each other for no reason.

**Comment by iangilman** [comment]
In fact, these random changes to the config file mean there are always merge conflicts when trying to merge branches in a project that uses the CodeKit config. Please tell me I'm wrong, but I don't see how anyone can actually use CodeKit in a shared repo until this issue has been resolved.

**Comment by lklepner** [comment]
My team is experiencing the same problem.

**Comment by iangilman** [comment]
For what it's worth, it was relatively painless to switch over to using http://gruntjs.com/ instead of CodeKit for my project: https://github.com/iangilman/interchange/blob/master/grunt.js

Of course I'd still rather be using CodeKit. :-)

**Comment by pdesterlich** [comment]
the problem isn't in the rewriting of the file, but it's the fact that the rewritten file is different from the previous one.

if you rewrite the file in the same way almost every cvs system can see nothing changed and basically ignore the file.

the problem is that the rewritten file is different, i think because it randomly sort project files every time in different ways.
i second the request for an option to disable the random sort: i have no problem if the refresh needs some seconds more (considering the fact that it's basically a background operation), cause right now i have to remember to discard file changes every time before i made a pull, this making me loose a lot of time (and i'm a single developer with 2 dev computers ... i can't imagine the pain in the ass for an even small team)
