### ISSUE TITLE
Able to add the same project twice - CodeKit then becomes unusable

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#45]
Check out this [screen recording](http://db.tt/87TRJwq).

**Comment by bdkjones** [comment]
Clever! 

I think I know what's going on here and will track it down.

**Comment by bdkjones** [comment]
Okay. 

What you've done is found a very awesome way of bypassing the logic that checks for existing projects before adding new ones. It gets better though.

Suppose you have a project that contains a folder called "Scripts" that's filled with files that codeKit is watching. Now, you take "Scripts" OUT of the original project folder and then add it to CodeKit as a separate project. Boom: instant model clusterfuck. 

This is because CodeKit technically doesn't stop watching files until you actually delete them off your disk. The app knows where they are at all times if they exist, even when in the trash or on another disk, etc. So when you move that scripts folder, CodeKit is still tracking it and everything in it. The app does this so that it can detect when you move the folder back into place in the project it was originally part of.

The solution, I believe, is to stop trying to be so damn smart. When a user moves a file/folder out of the project it was part of, the app is going to stop tracking it. If he later moves it BACK into the project folder, then he can click "refresh" to capture that change, just as he would if he added a new file from scratch. 

This will stop the ridiculousness and simplify life.

**Comment by bdkjones** [comment]
Also, you know how the app didn't show you that "broken" project once you started it when that project had been deleted? It was still there, in the app's model... but (and this is the good part) there's a RACE CONDITION in NSTableView when used through bindings that prevents it from loading data into the view if you tell it to do so too early after the app starts up. 

I love it when I find problems in Apple's frameworks. I've created a solution and the app will damn sure show you the data it has in the model, even if it processes that data faster than Apple's tableViews can keep up!

**Comment by paulyoung** [comment]
If there's an obscure bug to be found, I'm your man!

**Comment by bdkjones** [comment]
This also introduced another lovely issue:

Suppose you have two projects added to CodeKit and then you go to the Finder and drag one project's folder into the other. Instant catastrophe. No crashes, just a completely borked up model in both projects. 

So, from now on, if you do this, the project (X) you move into another project's folder (Y) will result in X being immediately deleted as a project and Y being refreshed to capture the new files. This does mean that any custom settings on files in X are discarded. This is completely appropriate for two reasons:

1) Those custom settings may no longer apply: import links between javascript files may point to files outside the project, depending on which folder you moved where, etc. Likewise, @import links in CSS files may no longer apply, etc.

2) People who move one project into another are dumbasses. And this way, they'll only make that mistake once.

**Comment by paulyoung** [comment]
All of these changes seem perfectly reasonable to me.

**Comment by bdkjones** [comment]
Okay, all of this nonsense should be fixed as of build 3540.
