### ISSUE TITLE
LESS @import syntax

### ISSUE THREAD

**Issue by nicooprat** [bdkjones/CodeKit-1-Old#456]
Because of some weird issue my colleagues working on Windows had with their compilers (won't deep into the details here), we had to write our imports like this :

```
@import url('inc/vars.less');
```

Codekit was dealing fine with this, until the very last version. Now, all files imported with this method are no longer recognized as imported, neither set to "don't compile directly". Of course it still works with the "official" method which would be :

```
@import 'inc/vars.less';
```

Is there any reason why Codekit changed its behavior ? Any chance to see the two syntaxes to be "accepted" again in the future ? 

Thanks.

**Comment by bdkjones** [comment]
the url() syntax is supposed to be used for resources that aren't local. CodeKit assumes that these items don't exist in the local filesystem, but rather are on the internet somewhere. Therefore, there's no point in linking to them because CodeKit can't tell when a file on a remote server is changed.

d

**Comment by nicooprat** [comment]
I understand, and I used to write these imports the good way. But for now I'm forced to use an older version of Codekit, because I can't update my LESS imports, otherwise my Windows colleagues won't be able to compile. Stuck.

**Comment by bdkjones** [comment]
1.4+ now handles URL syntax.

**Comment by nicooprat** [comment]
Glad to hear, thanks.
