### ISSUE TITLE
Wrong scss file is being compiled

### ISSUE THREAD

**Issue by titovm** [bdkjones/CodeKit-1-Old#479]
After a recent update (1.4.1 (8241)), when saving a "_file", included into main style, wrong file is being compiled. After several restarts and refreshes it keeps telling me, that it is being imported by a file, having no connections to any of the files.

**Comment by bdkjones** [comment]
I'll need a demo project that shows the issue.

**Comment by titovm** [comment]
sure: https://dl.dropbox.com/u/2157468/demo-project.zip
compile "_custom.scss"
worked with this project for the last month

**Comment by bdkjones** [comment]
The download link is 404-ed.

**Comment by titovm** [comment]
So the error still persists and i have to use compass the old, terminal way. Makes me think, why i paid for the software...
Really don't know, why the link doesn't work, maybe it was the HTTPS http://dl.dropbox.com/u/2157468/demo-project.zip

**Comment by titovm** [comment]
Updated to latest version, started with a shift, still same error, internal sass linking does not work.

**Comment by opb** [comment]
Hi

I thought I'd download your project for fun, but I'm unclear exactly what
the issue is. Can you be more specific?

**Comment by opb** [comment]
what is _custom.scss supposed to be imported by?

**Comment by bdkjones** [comment]
There are a couple things going on here.

First, you've got a tangled web of imports. For example, you're importing the "variables.scss" file into three other files that each then get imported into the main "styles.sass" file. You're importing _mixins all over the place as well. That's not correct.

What you need to do is set up a "master.sass" file. This file does nothing but import the others in the correct order. You'll want an order like this:

```
@import variables
@import mixins
@import layout
@import custom
```

Now, the ONLY file that gets directly compiled in this project should be the "master" file. All others simply get imported into that one. This means that you should NOT be importing your variables file into, say, mixins, layout, and custom. There is no need. Because the variables file is imported FIRST in the master file, those variables will be available when the subsequent files in the list are compiled. 

Secondly, while it's technically possible to mix Sass and Scss files together, that's untested in CodeKit (because you're the very first person I'm aware of that's done it!) I have to dig a little deeper to see if that's part of the issue in this case, but the first thing I need you to do is restructure the stylesheets correctly so that they aren't a tangled web of import statements all over the place. (I am almost positive that restructuring will resolve this issue.) Plus, it will also eliminate duplicated CSS code in the compiled output, which makes your file smaller and your website faster!

**Comment by bdkjones** [comment]
Also, in Sass/Scss it is common practice to omit the underscore from filenames in import statements. The underscore indicates a "partial" file --- one that is not mean to be compiled by itself, but rather imported into another file. You add the underscore so that you can quickly see these files in the Finder, but you don't include the underscore in the @import statement.

**Comment by bdkjones** [comment]
Ok, I restructured the imports as explained above, by creating a "master" file that imports all the others. I also added the underscore to all the other file names to indicate that they are partials, which are meant only for importing.

You can download the revised project here: http://dl.dropbox.com/u/25530182/corrected-project.zip

This has solved the issue. When you save any of the partial files (such as "_custom.scss"), the "master.sass" file now compiles, as you would expect.

**Comment by titovm** [comment]
This is a "Basic" starter theme for drupal (http://drupal.org/project/basic), they had this structure for the last couple of years and i was successful using it on many other projects, while using CodeKit the error appeared after the latest updates and using Compass in terminal doesn't give any errors (i tried both versions of SASS in CodeKit the one, that's installed on my machine and CodeKit one).

Thank you, @bdkjones for the insight on SASS file structuring, especially about the underscores, i will see this method in my future projects. And it looks like i'll have to make my own version of a starter theme, which was on my mind for quite a while, after redoing some cleanup work over and over again.

To @opb :
_custom.scss (changed to sCss by me on purpose, because i don't like the indenting style of sAss) is being loaded by style.sass (left as is, except for the @import "_custom.sCss"), when saving _custom.scss a totally different file is being compiled, like tabs.css or a _custom.css is being created.

While writing this, you restructured the project, thank you, as i said, i got the idea.

**Comment by bdkjones** [comment]
Sure thing.

Not everyone knows how to properly use @import statements, including the folks at Drupal. They really should have known better. The basic project you sent me was a mess. If you look at other projects such as Twitter Bootstrap, you'll find those developers follow the approach I've outlined above, which is the correct way to build modular Sass/Less frameworks.

Just a heads-up: you'll want to make sure I got the order right in the new "master.sass" file. You're much more familiar with the code than I am, so definitely verify that those files are imported in the correct order!
