### ISSUE TITLE
PNG optimization has no effect

### ISSUE THREAD

**Issue by paulyoung** [bdkjones/CodeKit-1-Old#48]
I made a copy of a png and optmized it using ImageOptim. The filesize reduction was 18.5%.

I tried another copy using CodeKit but the initial size and current size stayed the same.

**Comment by paulyoung** [comment]
Also I think 'Optimize' is more appropriate than 'Minify' but that's just my two cents.

**Comment by bdkjones** [comment]
1) "Optimize" is definitely better.

2) ImageOptim runs PNGCrush by attempting all 110 "modes." Currently, CodeKit runs PNGCrush with the usual defaults, which tries just the 10 most common "best" modes that apply to 90% of all cases. I did this because it's a good balance between speed and reduction. I also didn't enable any of PNGCrush's "lossy" optimizations. 

I debated offering a preference panel to configure PNGCrush. I may still do so.
