### ISSUE TITLE
Codekit doesn't catch changes in codekit-config made in other computers

### ISSUE THREAD

**Issue by pdesterlich** [bdkjones/CodeKit-1-Old#488]
Setup: i have 2 macs and i write code in both, using a git repo to sync; i write some code in one mac, commit & push, then move to the other, pull & merge, write some code, commit & push, move & so on
There's the same apps (codekit included) & project dirs in both.

In one of my project i created a libs.js, and in codekit i manually set up it for importing other .js files, so codekit can concatenate + minify and everything works like a charm. Then of course i commit & push, and move to the other mac.

As i read somewhere i uncheck tha flag near the project line in codekit, then pull & merge, then recheck the flag.
At this point i expect to see that libs.js has imported files in it's properties, but ... no way! all the files are in the main list but codekit does not get the imports i made in other mac.

As of now the only way i have to make it work is to completely remove the project from codekit prior to pull & merge, then after the pull i add the project and i have all files and imports correctly set up.

Given the fact i switch computer multiple times a day, this is a pain in the ass for me (i can't imagine for an even small team).

**Comment by opb** [comment]
Have a look at issue 409.

What version are you running?

**Comment by pdesterlich** [comment]
1.4.1 (current)

**Comment by bdkjones** [comment]
Yep. 

CodeKit uses the config file to set up a project when you add it to the app. After that, it does not use that config file again. To have the changes you made on Mac #2 (the new manual, drag-dop import links) show up in the project on Mac #1, you'll need to remove the project from CodeKit on Mac #1 and then re-add it. 

This is deliberate behavior. The reason is simple. Say you establish a bunch of import links between two files by drag-dropping in CodeKit. The app exports a config file containing that information. Now suppose you delete some of those import links. This time, when CodeKit refreshes, it has a problem:

```
According to the config file, there should be FIVE import links for files A and B. 

According to the state of the project in the app, there are only TWO import links for files A and B.
```

What do we do? If we sync the project state to match the config file, then the app would re-create the links you just deleted! That's why CodeKit uses the config file to set the project state only once, when you first add the project to the app. From then on, it will always respect the "internal" state of the project within the app.

**Comment by pdesterlich** [comment]
According to your response, your suggestion to "uncheck the box next to the project in the CodeKit window before pull & merge, then re-check the box after the operation" should change in "remove the project from CodeKit before pull & merge, then re-add the project after the operation" ...

To solve the situation in your example i think the key is in who change the config-file: 
- when codekit refresh, the config file is written / updated by codekit itself, so it's the app who rule (means nothing should be done in the app)
- if the config file is changed externally (means it's not codekit itself who has updated it, but you can catch external modification in file as you do for every other project file) then update the app accordingly (automatically or only if a relative option is checked) (i know, i'm an option maniac)

**Comment by opb** [comment]
One way of looking it is that the CodeKit GUI could simply be a graphical frontend for the config file. So CodeKit could be thought of as three elements:
- The backend, all the libraries etc, which do the heavy lifting. Details of what to do are taken from the config file.
- The config file itself
- The GUI, for creating links and making config changes, written to the config file.

So when you make changes within the CodeKit GUI, these have to be 'committed' to the config file, before they take effect. A commit to the config file then triggers the backend to do its thing (as well as the standard file changes within the project).

You could make it so that every project has its own config file. The current global config options could be turned into a method for specifying defaults when adding a new project. These can be then overwritten by editing the options for each individual project.

In this way, the config file is stored with a repo and becomes the main focus, in a way. The CodeKit application then provides a method for editing this file (just as one would edit any file in a repo) along with the ability to actually do the tasks on the developers' local machines.

Just some random thoughts. I use CodeKit by myself, so it makes no difference to me!
