### ISSUE TITLE
Feature request: Delimit included files in output file with comments

### ISSUE THREAD

**Issue by grahambird** [bdkjones/CodeKit-1-Old#505]
It would be useful if CodeKit delimited imported files (in the output) with comments...

myfile.css
...
/\* CodeKit: layout.less starts _/
...contents of COMPILED layout.less
/_ CodeKit: layout.less ends */
...

This is because when troubleshooting a large output file that's generated from many included LESS files it can be difficult to work out which bit you're looking at. I know I could write these comments myself (I do in fact) but it would be cool if CodeKit could auto-generate them.

**Comment by bdkjones** [comment]
Hmm, it's not a bad idea. Two things:

1) Source Maps are coming. Sass already has them and I would expect Less to adopt them in the future. They are _much_ more powerful than simple comments like this, so that may solve the issue.

2) This is something that would need to be added to the Less compiler itself, because that's what generates the output. Please open an issue on the Less.js GitHub page. Thanks!
