### ISSUE TITLE
Feature Request: Optional suffix when generating output to different directory

### ISSUE THREAD

**Issue by bmatzner** [bdkjones/CodeKit-1-Old#510]
Love the app! When setting output paths to a different directory, the required suffix is not necessary and not always desired. Example: I'm using RequireJS to load JS files, the source files are outside of the public webserver path, and using CodeKit to generate JS in the public files, in this case the additional suffix is not desirable and not having one will not cause problems with overwriting the source file. It would be great if you could make the suffix optional if output path is not set to same directory. Thanks for considering!

**Comment by bdkjones** [comment]
Yea, you'd _think_ this would be the case. 

In reality what happens is that folks go and change the output path without realizing that they've set it to the same directory as the source file. And then, before you know it, I've got an angry email in my inbox shouting about how CodeKit destroyed hours of work because it overwrote a file and the user didn't have a backup, so now they have to waste a full day redo-ing things, etc.

The suffix is required as an idiot-proofing measure. There is one way around it. Once you've got the file created, go to the Finder and rename it by removing the suffix. CodeKit will notice the change and update the output path of the original file accordingly.
