### ISSUE TITLE
Please add ignore settings to `codekit-config.json` + Skipped Items issue

### ISSUE THREAD

**Issue by firedev** [bdkjones/CodeKit-1-Old#512]
Correct me if I am wrong, but I would expect ignore settings to be saved to `codekit-config.json`.

Just now pulled changed on another computer and all the previously ignored files and folders are back in business.

And they don't go away after I add the folder to Skipped items. Tried Cmd-R, restart, nothing.

![](http://d.pr/i/tfFU+)

PS. What does `compassEnabled` setting mean? Gone after I have installed compass gem.
![](http://d.pr/i/jaak+)

**Comment by bdkjones** [comment]
The "Skipped Items" list is not saved in project settings because it is not a project-level preference. The skipped items list is UNIVERSAL, across all projects.

It's also consulted _only_ when adding a project to CodeKit. Subsequent refreshes do not consult the skipped items list (mainly because it would slow down refreshes slightly).

Finally, this is all changing in 2.0. At that point, skipped items will be project-level options.

**Comment by firedev** [comment]
That's a pity. Mind if I ask how it is going to be handled in v2.0 and what is the timeframe for it's release?
