### ISSUE TITLE
UX: File list should be formatted as a tree to reflect what it actually is

### ISSUE THREAD

**Issue by fform** [bdkjones/CodeKit-1-Old#515]
Flat formatting every file into one giant list doesn't make sense.

Why take away the fact that these files are organized into folders in the first place? When I have thousands of files in my project, why do I have to scroll so far just to get from folder to folder?

**Comment by bdkjones** [comment]
;)

I'm going to close this because... well, you'll see.

**Comment by fform** [comment]
How close are you to a public release on whatever it is that fixes this stuff? I'm pretty much at a point where I can't use this for anything other than experimentation projects that don't have a real folder structure. I'd love to test the new version if it can provide some answers to these problems

**Comment by bdkjones** [comment]
CodeKit 1.0 was never designed to organize your projects or view their structure. CodeKit is a companion app that is meant to run silently in the background -- the only time you interface with it is when there's an error. To organize your project, you'd use the Finder or the outline view in your editor of choice. 

As for future release schedules... that, I'm afraid, is classified.

**Comment by fform** [comment]
But that's not true. "the only time you interface with it is when there's an error"

Or when I need to manually configure every file I add to a project because codekit can't ignore a folder.
Or when I have to manually change the compass runtime because CK doesn't support adding frameworks
Or when CK can't use RVM for no reason or specify an external Ruby runtime
Or when I need to tell CK to set the output path to be something other than the original path.
Or when I need to tell CK to ignore external JS libs because I don't want to lint/concat/compile them
Or in every project where I need to manually set the tab to livereload

My point being: If it's supposed to be a set once and forget it. You've failed. If it's a tool I'm supposed to run alongside my work, then it's inefficient. Typically, you'd want the time-savings to make up for the time-lost in setting things. I feel like all I've done since I bought this thing is try to make it work and fail.

As for your comment about future release schedules: Classified? I don't know if you're joking – hopefully.

**Comment by bdkjones** [comment]
1) Preferences > Skipped items. Ignore as many folders as you'd like. You'll need to edit this list before adding the project to the app so that CodeKit knows to skip the folder when it scans it. 

2) CodeKit can't use RVM for some technical reasons. But you can easily run the "system" command on RVM to tell it to place your gems in standard locations. At that point, you can have CodeKit use the external gem instead of the bundled ones. However, this is only necessary for Compass when you want to use 3rd party Compass plugins --- and I'm working on solving that issue so you won't need to switch to an external Compass gem to do it. 

3) In general, you should set the starting defaults for output paths (in the Languages pane of the preferences window) to match your most common project setup. For example, most folks have their javascript files in a folder called "scripts" and they minify those files to "scripts/min". You can set the default starting output paths so that CodeKit naturally configures projects the way you most commonly want them configured. Another example would be Sass files. Most people have "styles/sass" and then place the output files in "styles/css". 

4) In the case where you need to rapidly find a single file, it's fastest to simply type the name into the search bar. "jquery", for example. Much faster than expanding several levels of an outlineView. You can also use the "filter" bar at the top of the files list. Most folks have only a handful of stylesheets in an average website, so it's easy to select the "styles" tab and then scan the reduced list for the one you're looking for. 

I acknowledge that the app's UI is not perfect and I definitely have great things coming. But at the same time, if you configure the default output paths appropriately, then use the filter bar and the search bar effectively, I think you'll find that it's much faster!

As to the last point, I'm afraid I can't comment on future releases. I'm just a single guy writing software out of my house, going as fast as I can. CodeKit is absolutely under full-time, active development and I'm going to be improving the app for years to come.
