### ISSUE TITLE
Feature Request: Smarter Browser Refresh

### ISSUE THREAD

**Issue by JRGould** [bdkjones/CodeKit-1-Old#584]
Generally I'm really loving codekit but one annoyance that I have is the way browser refreshes are handled.

I'm often working on a few projects at a time with multiple tabs open for each project - I'm using the "Any tabs with URLs that contain these strings:" setting to only auto-reload pages on my development server, but this will still cause a refresh of a lot of tabs that don't need to be refreshed for the project that I'm working on which can slow down the refresh of the tab I actually want refreshed, and can cause annoyances with background tabs being refreshed and clearing the page state. This will also refresh tabs that mention the url in a query string, such as Browser Stack, which is unwanted.

I think all of these issues could be resolved by adding a little more configurability to the refresh settings:
-Allow project-level refresh settings, which I imagine could prevent refreshing tabs from other projects when a project file is saved
-Allow regular-expressions for matching urls or just some more matching logic like "URL Starts With:", "URL Contains:", "URL Ends With:"
-Would love to be able to chose which instance of Chrome to refresh (Chrome, Canary, Chromium Build) or integrate with a Live Reload style extension that can be toggled on and off in the specific browser

**Comment by bdkjones** [comment]
Hi JR,

I'm looking at ways to provide more fine-grained control of this. I don't want to go the regex route because regex is a dark, sad hole of confusion and despair to most folks (including me). I don't want to go the browser extension route because that eliminates the magical "holy shit, how does that work!?" feeling.

In the meantime, I recommend setting CodeKit to reload only Safari or Chrome and then open pages in each browser based on whether they should refresh or not.

**Comment by JRGould** [comment]
Totally understandable. Thanks for the reply, and thanks for making a great app!

**Comment by bdkjones** [comment]
No longer applicable in 2.0. Magic coming.
