### ISSUE TITLE
Bug: CodeKit not responding / 100% CPU usage

### ISSUE THREAD

**Issue by leizhao4** [bdkjones/CodeKit-1-Old#599]
Yes, I know I can press Shift and launch the app. It works, but it clears all my project settings, and costs me half a hour to fix them and get back to work. And after a few days, it happens again! Can we have a 'real' fix for that?

**Comment by leizhao4** [comment]
Crash report: https://gist.github.com/leizhao4/8fcee952587b1494a1d4
Hope it helps.

**Comment by bdkjones** [comment]
If this keeps happening, it's likely because you're corrupting the model file by doing something like switching Git branches without first unchecking the project in CodeKit. Changing thousands of files all at once like that will send the app for a loop and almost always corrupt the model file, resulting in the behavior you're seeing.
