### ISSUE TITLE
No output written

### ISSUE THREAD

**Issue by ginghamsburg** [bdkjones/CodeKit-1-Old#64]
I have a less file that imports 2 other less files. However, when it compiles the output file is empty. If I have Bless enabled the log tells me that "Source CSS file contained 0 selectors. No changes made."

The files are the css file that comes with the html5 boilerplate collection http://html5boilerplate.com/ and a less elements file obtained from http://lesselements.com

I run a standard user account and the input and output files are read/write-able by me (see below).

[~/Sites](master): ll /Users/chris/Sites/lib/css 
total 48
2900696 drwxr-xr-x  4 chris  nobody  -  136 Nov  7 12:23:40 2011 ./
2341335 drwxr-xr-x  7 chris  nobody  -  238 Nov  7 11:59:59 2011 ../
2900745 -rw-r--r--@ 1 chris  nobody  - 9934 Nov  7 12:23:51 2011 boilerplate.less
    com.macrabbit.Espresso.metadata.uncompressed      98 
2899899 -rw-r--r--@ 1 chris  nobody  - 4685 Nov  7 14:17:09 2011 elements.less
    com.apple.FinderInfo      32 
    com.apple.ResourceFork   286 
    com.apple.TextEncoding    15 
[~/Sites](master): ll /Users/chris/Sites/pub/themes/site_themes/ginghamsburg/css 
total 16
2891200 drwxr-xr-x  4 chris  nobody  - 136 Nov  7 11:04:56 2011 ./
2891198 drwxr-xr-x  6 chris  nobody  - 204 Nov  6 14:59:02 2011 ../
2899952 -rw-r--r--  1 chris  nobody  -   1 Nov  7 14:11:42 2011 styles.css
2900040 -rw-r--r--@ 1 chris  nobody  -  50 Nov  7 12:44:00 2011 styles.less
    com.apple.FinderInfo     32 
    com.apple.TextEncoding   15

**Comment by bdkjones** [comment]
Hi Chris,

If the two less files you're importing are simply full of variables, mixins, etc, they won't produce any output. You have to define a selector that uses those elements.

In other words:

.myAwesomeMixin() {
    color: white;
    font-size: 50px;
}

doesn't compile to CSS until you do something like this:

#anElement {
    .myAwesomeMixin();
}

So much of the lesselements stuff doesn't translate to CSS until you use it. 

If this doesn't describe what's happening, please email me the files at bryan at incident57 dot com and I'll take a look. Thanks!

**Comment by ginghamsburg** [comment]
That is the case for the elements.less file but the boilerplate.less file is simply a straight-up css file renamed to boilerplate.less so it can be included as part of a framework. Since Less is a superset of CSS, shouldn't the standard css declarations in that file work with the less compiler and simply be output as minified css?

**Comment by bdkjones** [comment]
Yes, they should.

How are you importing the file? @import "file.less"; or @import url(file.less); Use the first syntax. Are you sure the path to the file is correct in the import statement? That is, you've used the appropriate relative syntax to point to the imported file relative to the base file? eg: @import "../../fileToImport.less";

I just downloaded the boilerplate source and found the only CSS file in the project: style.css (looks like a reset stylesheet.) I changed the extension to style.less and then created a new file called "base.less" in the same folder.

Base.less has exactly one line:

@import "style.less";

When I add the folder to CodeKit and save base.less, the appropriate CSS file is created and all of the selectors from the boilerplate stylesheet appear correctly.

**Comment by bdkjones** [comment]
If you're using the boilerplate less file as part of a CodeKit framework, you don't need the relative link syntax. Indeed, it will fail to find the file if you supply anything other than the filename. 

My best guess would be that you're using the url() import syntax. If so, don't. That's really meant to import something at an absolute URL. Anything that's in the local filesystem should be done with a standard @import "file.less"; statement.

CodeKit ignores any import statement with the url() syntax because it assumes that the file is not local.

**Comment by ginghamsburg** [comment]
Sweet mother of God forgive me. I omitted the frickin' semicolons. Sorry to waste your time.

Thanks.

**Comment by bdkjones** [comment]
Ha. That's interesting... I wrote CodeKit's parser to look for a newline or end of file marker. Don't tell anyone, but you could technically do this:

@import somefile.less

and CodeKit would pick that up just fine. 

The Less compiler, however, is a bit more picky. It DOES require semicolons because it's a true compiler that tokenizes the file and all that jazz. CodeKit's parser does not go through all that trouble because it doesn't need the tokens. 

Glad you got it working!
