### ISSUE TITLE
Add postprocesor like Autoprefixer

### ISSUE THREAD

**Issue by soundake** [bdkjones/CodeKit-1-Old#653]
https://github.com/ai/autoprefixer

I think that this is very usefull tool for forgetful users.

**Comment by bdkjones** [comment]
Not needed. Just use a mixin in Sass, Less or Stylus. Libraries like Bourbon, Compass and Bootstrap already have them available.

**Comment by ai** [comment]
@bdkjones Autoprefixer is better, that mixins libraries:
- It contain only actual prefixes by Can I Use. No more `-moz-border-radius` and esle.
- You don’t need to think, what CSS property need mixin, and what doesn’t. You just write CSS by latest W3C specs and it’s just work. For example, for `@keyframes` or `::selection`, `::placeholder` selectors you need to learn new API instead of basic CSS.

BTW, Paul Irish [recommend Autoprefixer](https://twitter.com/paul_irish/status/352567732044169218).

CSS Tricks publish today good article with explain why Autoprefixer better and how it works: http://css-tricks.com/autoprefixer/

**Comment by jozzs** [comment]
It would be really useful. Most of times you don't remember if you need to use a mixing or not. And if you do, you have to remember how the mixin was.

**Comment by Grawl** [comment]
Agree. Want to see Autoprefixer in CodeKit. Also, Prepros already have it.

**Comment by piersolenski** [comment]
+1, not having to refer to additional syntaxes would speed up workflow considerably! Plus only up to date prefixes means less css bloat. Would love to see this in the next Codekit

**Comment by ScottSmith95** [comment]
Yes, Autoprefixer is a more elegant way of adding prefixes to you code than just using Sass mixins. I'd love to see support in CodeKit.

**Comment by xxsnakerxx** [comment]
+1. Want to see Autoprefixer in CodeKit.

**Comment by bdkjones** [comment]
Alright, you guys have convinced me. I'll add it.

**Comment by ScottSmith95** [comment]
Thank you for listening and being open to new ideas!

**Comment by piersolenski** [comment]
Yay!

**Comment by xxsnakerxx** [comment]
yeah!

**Comment by jozzs** [comment]
Thanks! You rock!

**Comment by jrdn91** [comment]
Out of curiosity is there anywhere we can see updates on what's being worked on and what will likely be the next things to be added into the project? A blog, or do you post that sort of thing on Twitter maybe?

**Comment by bdkjones** [comment]
Once I release 2.0, I'll publish a bit of a roadmap for where I'm going. Until then, I see no reason to give the bevy of knock-off apps any more ideas. They've already successfully copied everything I do.

**Comment by Bjorn-Eric-Abr** [comment]
+1 It will be awesome.

**Comment by NazarkinRoman** [comment]
What about Autoprefixer in Compass projects?

**Comment by Grawl** [comment]
Autoprefixer is a postprocessor, it works with compiled CSS, not with SASS.

**Comment by NazarkinRoman** [comment]
I know, but why Autoprefixer isn't available for Compass? 
For pure SASS, Less and Stylus it is available.
