### ISSUE TITLE
Using GIT and CodeKit

### ISSUE THREAD

**Issue by jankeesvw** [bdkjones/CodeKit-1-Old#67]
I was using CodeKit and everything was working great, until i used GitFlow to finish a feature. The app couldn't handle the file changes.. It crashed... Could find a crash report...

**Comment by bdkjones** [comment]
Yep.

See http://incident57.com/codekit/help.php and read the paragraph about Git and SVN. It's a known issue and I'm working to find a way to handle Git changes. For now, the only safe source-control actions to perform while a folder is in CodeKit are commits.

-Bryan

**Comment by jankeesvw** [comment]
Ah thanks! I didn't see the FAQ... But I can close and reopen the app when switching branches right?

**Comment by bdkjones** [comment]
Theoretically... yes. 

The app should start back up and refresh the project to capture the new filesystem state. Let me know how that works for you.

**Comment by bdkjones** [comment]
Okay, after some research, I think it might be possible to have CodeKit just automatically adapt when you perform a Git action that dramatically and instantly changes the contents of your working directory.

The only issue I don't have a solution for is what happens if, say, you switch from branch A to branch B and in B, there are a whole lot of files that don't exist in branch A. CodeKit won't detect those files until you perform a refresh. I'm thinking about trying to possibly detect a change in the hidden .git folder within the working directory and, whenever that hidden folder changes, have the app refresh the associated project. 

But that will only work if the user adds the root folder of the working directory as a project. If he adds some subfolder, then CodeKit won't know about the hidden .git folder. 

That's pretty easily remedied with a rule though: "If you intend to use CodeKit with Git, you must add the root folder of your working directory."

Brainstorming. But I think this is doable.

**Comment by samalone** [comment]
My impression is that git itself considers a folder to be a working folder if it or any of its parents contains a ".git" file or folder. So perhaps it's worth traveling beyond the project directory to check for a .git file/folder.

If my memory serves, .git is a file rather than a folder if you specify the "--separate-git-dir" to git clone. In that case, the .git file contains the path to the actual .git directory.

**Comment by bdkjones** [comment]
base42 -- 

Can you find that crash report for me? I've been working on Git support and have made some changes to CodeKit that allow it to adapt to basic changes in your working directory (such as files disappearing when you switch branches).

But I need some more info on what the specific causes of the crash are. Alternately, if you can provide a git folder that crashes the app when you do something (switch branches, merge, rebase), that would also be useful!

**Comment by jankeesvw** [comment]
I sure can, I tried finding the crash report in the console right after the crash but I couldn't find it. Where do I look for it?

I use git-flow and switch a lot between feature branches they have a lot of new files most of the time..

**Comment by bdkjones** [comment]
The crash log should appear in ~/Library/Logs/CrashReporter

**Comment by jankeesvw** [comment]
Sorry, it isn't there..

I will try to crash it later today.

**Comment by bdkjones** [comment]
Be sure you download Beta 2 first.

**Comment by bdkjones** [comment]
Okay, I haven't heard anything about this since Beta 2 went live and no new people have emailed me to complain about it, so I'm closing the issue.

**Comment by jankeesvw** [comment]
Crashed it yesterday, when I switched branches.. but still no crashlogs.. sorry!
