### ISSUE TITLE
Invalid character error on compile Mavericks

### ISSUE THREAD

**Issue by matt-tyas** [bdkjones/CodeKit-1-Old#683]
This has occurred on two of my machines since the Mavericks update.

Syntax error: Invalid US-ASCII character "\xE2"

Happens on every compile. 

I have updated to 1.9.

Thank you.

**Comment by bdkjones** [comment]
Add this to the VERY FIRST line of your sass stylesheet:

@charset "UTF-8"

**Comment by Motifsky** [comment]
I just upgraded to Mavericks this AM and started getting similar character errors using Gumby Framework.  Using CodeKit 1.9 (8348).  I already have the @charset "UTF-8" character set in place and still was receiving the errors.  I tracked it down to characters in the _entypo.scss file and some other mystery characters in two other files.  _grid.scss and _forms.scss.

In the entypo.scss file  each font is mapped like this

$entypo-icon-note: \266a; 
$entypo-icon-picture: \1f304;

for all of the fonts the started with /1f they displayed on github preview and in sublime text3 as an 'icon' instead of as an alpha numeric code.

![entypo](https://f.cloud.github.com/assets/962496/1393279/96043f48-3c17-11e3-87e7-5f3df2246fad.jpg)

When I replaced the icon with the correct code, the compile error went away.   For the other two files that were throwing errors in CodeKit... _grid.scss was a line the had nothing but an ending bracket, which I deleted the line and simply retyped a new end bracket.  The other was a comment line in _forms.scss, I simply deleted the line.  Now the entire compass project compiles without issue.

**Comment by bdkjones** [comment]
It's due to Ruby 2.0 included in Mavericks. The newer ruby is more strict with encodings and it looks like Apple may have misconfigured the default encoding for Ruby. 

I'm working with the Sass team to track down the issue and come up with a good fix.

**Comment by matt-tyas** [comment]
HI, 

Thanks for your quick response on this. The above fix did not work for me and the error just moves to the next line if I delete the one above. I will have to wait for your fix, thanks for looking into it.

Codekit is a great thing, cheers for your hard work.

**Comment by bdkjones** [comment]
Releasing 1.9.1 in a few minutes, which resolves this issue.

**Comment by Bechrissed** [comment]
I'm using 1.9.2 and i'm still having problems with this issue. Anything I can do beside adding the charset?

I am using the internal compiler and i closed Codekit and restarted holding the shift button ...

**Comment by bdkjones** [comment]
Are you on Mavericks? Please send me the file that's showing the issue, along with any files it imports so that I can test it over here.
