### ISSUE TITLE
Append/prepend by filename

### ISSUE THREAD

**Issue by zagoruev** [bdkjones/CodeKit-1-Old#726]
Codekit 2 breaks appending/prepending js files using only filename not relative path.
So any of "old" projects using this feature won't compile properly.

And the paths with bower_components looks ugly.

Please bring back append/prepend only by filename.

**Comment by bdkjones** [comment]
Yea; this is covered in the help section for Frameworks. It's not possible to do only the filenames anymore because Frameworks are now allowed to have files with the same name in different folders. Giving up that limitation means that CodeKit can't just look for a filename and be sure that's the one you meant to import.
