### ISSUE TITLE
Causing reload of chrome pages

### ISSUE THREAD

**Issue by jluna79** [bdkjones/CodeKit-1-Old#74]
It's weird but when Codekit starts refreshing projects and templates it is causing the foreground tab in Chrome to start reloading non-stop.

Twice it happened and it only stopped until I quit Codekit

**Comment by jluna79** [comment]
I'm on Mac OSX 10.7.2

**Comment by bdkjones** [comment]
Are you using a Java-based editor?

**Comment by jluna79** [comment]
Nope, I'm using MacRabbit's Espresso … I am running a grails application though.

-jl

**Comment by bdkjones** [comment]
What the hell is a grails application?

**Comment by jluna79** [comment]
An application proggrammed (and running) on Grails :P (http://grails.org/)  in short, it does uses the JVM.

-jl

**Comment by bdkjones** [comment]
Does the problem persist when you're not using grails?

**Comment by jluna79** [comment]
I think not.. the problem appeared when running such app, without running grails I've had no problems so far.

**Comment by bdkjones** [comment]
Okay. This is the same issue I've seen with other Java-based crap.

Maybe someday I'll sit down and try to support Java-based stuff. But Apple has officially deprecated Java support on OS X, most Java-based apps are utter shit because they attempt to be cross-platform, and I have no time to waste on the 1% of people who use them. No offense!

The issue is that Java apps don't save files using the normal OS X APIs, so everything gets mucked up.

**Comment by jluna79** [comment]
Fair enough ... just one final note:

I'm not only "using" a java-based web (cr)app... I'm developing it (and Java is very generalized even if we don't fully like it)... since Codekit is a developing tool it is contradictory that it both helps and causes troubles for developers. 

The problem, as long as I have investigated is when running the web server (Tomcat in this case, yup, java-based). Therefore what I can make of it this should only appear on java-based webservers running on developer machines... 1% seems about right... still, maybe you can add this as a "known issue" with the advice "quit and open code kit again" on the FAQ :P

**Comment by bdkjones** [comment]
Yea, I need to add a Java warning to the website.

The issue is pretty complex and I've done a fair amount of digging in the past, as this problem also manifests with Less.app. The Java bridge (the thing that actually allows Java to run on top of OS X) does not modify/save/edit files in the same way that fully native apps do. 

CodeKit taps into the kernel of OS X and says, "Tell me when you make a change to any of these files: X, Y and Z." When you save one of those files, the kernel actually deletes the original file and writes a new one in its place. CodeKit gets a message that says, "Hey, this file was just deleted" and it actually gets that message BEFORE the new file is in place and ready to be read. But that's okay, because the kernel serializes access requests and doesn't allow CodeKit to open the file before the new version is finished writing.

Something about that timing gets all screwed up when the Java bridge is the one writing the file. There's nothing I can do without seeing the implementation of the bridge. There's also several open bugs filed with Apple from other developers who have noticed that Java and kernel queues (the thing CodeKit uses to watch files) don't play nicely together.

Apple knows, they just don't apparently care about Java. The bottom line is that there's nothing wrong with my code and nothing I can do to fix this situation on my end.

**Comment by jluna79** [comment]
Yup,  I think a "Java beware!!" warning will do :P ... Thanks for the insight! :) ...
