### ISSUE TITLE
Compiling fails on valid CoffeeScript

### ISSUE THREAD

**Issue by doomspork** [bdkjones/CodeKit-1-Old#75]
I'm not entirely sure why this block of code is failing within CodeKit, but it is.  The same error is generated even if the `switch` is swapped for a `if/else`.  The use of `window.location.replace(response.data.location)` has no apparent impact.  The Try CoffeeScript feature on the homepage is able to successfully compile this snippet.
### Code

```
switch response.status
  when 'success'
    window.location.replace response.data.location
  when 'failure'
    $.append('.errors') error for error in response.data.errors
```
### Error

Parse error on line 18: Unexpected 'LEADING_WHEN'
### Output from CoffeeScript's own web based parser

```
var error, _i, _len, _ref;

switch (response.status) {
  case 'success':
    window.location.replace(response.data.location);
    break;
  case 'failure':
    _ref = response.data.errors;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      error = _ref[_i];
      $.append('.errors')(error);
    }
}
```

**Comment by doomspork** [comment]
I was able to successfully compile after removing the previously generated files, reselecting the output directory, and recompiling.  All other attempts were unsuccessful.

**Comment by bdkjones** [comment]
Not sure what's going on, but I've updated the CoffeeScript components to the very latest version (as of 19 November) and your code compiles fine in the working build that's about to become Beta #4.

The CoffeScript updates included a bunch of bug fixes, so it's possible this was one of them and that the "trail" feature on the site was using the updated components. 

Either way, this seems to be fixed in build 4061.
