### ISSUE TITLE
Feature Request: Save project

### ISSUE THREAD

**Issue by webster** [bdkjones/CodeKit-1-Old#80]
When multiple developers are working on a project, it would be super helpful if CodeKit had a 'save project' feature, where the configuration could get committed to version control or passed around between the developers.  With this, each developer's preferences wouldn't override established project settings.

**Comment by paulyoung** [comment]
Agreed

**Comment by kilianc** [comment]
+1

https://github.com/bdkjones/CodeKit/issues/117

**Comment by bdkjones** [comment]
The problem with this is that the data CodeKit stores is _absolutely_ dependent on the local filesystem. That is, CodeKit remembers that file X is at this path:

~/Users/jSmith/Clients/Website1/styles/less/main.less

So if you "save" the project settings and then pass that file to someone else, who has the same project folder, but at this location:

~/Users/bJones/Projects/Client1/styles/less/main.less

Then the project settings are meaningless because CodeKit can't find the original files that contained those settings. And each of the two machines will have different identifiers for the same file (these are low-level file system attributes that the OS uses to keep track of files) so even if a file is in the identical path on the two machines, CodeKit will still not recognize the files as equivalents.

Thus, adding the feature would require some major overhauls in the way CodeKit works with the filesystem. It's a ton of work, but I'll keep the request in mind.

**Comment by oldskool73** [comment]
+1 for this, think it's a basic requirement for any kind of team or even a lone developer working across more than one computer.

**Comment by bdkjones** [comment]
Stay tuned later this week...
