### ISSUE TITLE
Why no bouncing in the dock when launching the app?

### ISSUE THREAD

**Issue by ddanielou** [bdkjones/CodeKit-1-Old#89]
Not that I lose sleep over it, but why is that?
Not to sound like a pedantic asshole, but this kind of feedback is here for a reason, namely to confirm that you clicked on the dock icon alright and no-need-to-click-again it's just taking me some time to launch now will you please be patient?

So, any reason for that? Less.app behaved the same, so I guess you actually meant it.

**Comment by bdkjones** [comment]
You know, I've never noticed this? 

This is not intentional on my part, but I believe I have an explanation. CodeKit allows you to run the app either from the Dock or the Menubar. Apple does not make this very easy. The APIs are designed to do EITHER a dock OR a menubar app. 

To get around this, CodeKit ALWAYS starts as a background process with no UI. Then, during launch, it looks at your preferences and, if you've picked to run the app in the dock, it transforms itself into a foreground app. Otherwise, it stays in "menubar land."

I believe this is the reason the dock icon does not bounce on launch --- CodeKit (and Less.app) aren't foreground applications when you launch them. I'll see if I can't hack together a little bouncing action.

**Comment by bdkjones** [comment]
Okay, after wasting an hour trying to get around Apple's framework, I've decided this can't be done.

I've filed a bug report with Apple telling them that Dock.app needs to bounce icons when it's told to transform a background application into a foreground app.

I CAN make the icon bounce with the animation you normally see when an app is requesting attention --- but that's a sharper, higher bounce than the little one that happens when you launch an app. I don't think the two are substitutes, so the better-looking option is to not bounce at all.
